// Aura slot: no gear, shown as effects around the raccoon. Each has an 11x11 icon.
import type { ItemDef } from '../types';

export const ITEMS_AURA: ItemDef[] = [
  {
    id: 'good_vibes',
    name: 'GOOD VIBES',
    rarity: 0,
    slot: 'aura',
    tags: ['tank'],
    desc: '+1 VIT, +1 LCK',
    icon: [
      '....kkkkkk.',
      '...khhhhhhk',
      '...khkkkkhk',
      '...khk..khk',
      '...khk..khk',
      '.kkkhk.kkhk',
      'kPhhhkkPhhk',
      'khhhMkkhhMk',
      '.kkkk..kkk.',
      '...........',
      '...........',
    ],
    bonus: (b, l) => {
      b.vit += l;
      b.lck += l;
    },
  },
  {
    id: 'sparkle',
    name: 'SPARKLE',
    rarity: 0,
    slot: 'aura',
    tags: ['scav'],
    desc: '+15% SHINIES',
    icon: [
      '..k........',
      '.kyk.......',
      'kyYyk...k..',
      '.kyk...kyk.',
      '..k...kyYyk',
      '.......kOk.',
      '...k....k..',
      '..kyk......',
      '.kyYyk.....',
      '..kOk......',
      '...k.......',
    ],
    bonus: (b, l) => (b.shinyMult += 0.15 * l),
  },
  {
    id: 'breeze',
    name: 'TAILWIND',
    rarity: 0,
    slot: 'aura',
    tags: ['speed'],
    desc: '+1 AGI, +3% DODGE',
    icon: [
      '......kkk..',
      '.....kiCCk.',
      'kkkkkkkkCk.',
      'kiCCCCCCk..',
      'kkkkkkkk...',
      '...........',
      '..kkkkkkk..',
      '.kiCCCCCCk.',
      '..kkkkkkCk.',
      '.....kCCk..',
      '......kk...',
    ],
    bonus: (b, l) => {
      b.agi += l;
      b.dodge += 0.03;
    },
  },
  {
    id: 'grumpy',
    name: 'GRUMPY',
    rarity: 0,
    slot: 'aura',
    tags: ['crit'],
    desc: '+2 STR',
    icon: [
      '.kkk...kkk.',
      'krrrk.krrrk',
      'krRk...kRrk',
      'krk.....krk',
      '.k.......k.',
      '...........',
      '.k.......k.',
      'krk.....krk',
      'krRk...kRrk',
      'krrrk.krrrk',
      '.kkk...kkk.',
    ],
    bonus: (b, l) => (b.str += 2 * l),
  },
  {
    id: 'fly_swarm',
    name: 'FLY SWARM',
    rarity: 1,
    slot: 'aura',
    tags: ['trash'],
    desc: 'END OF TURN: FLIES BITE A FOE FOR 4',
    icon: [
      '.k.k.......',
      'kikik......',
      '.kHk...k.k.',
      '..k...kikik',
      '.......kHk.',
      '..l.....k..',
      '...k.k.....',
      '..kikik..l.',
      'l..kHk.....',
      '....k......',
      '.l.....l...',
    ],
    fx: (l) => ({ flies: 4 * l }),
  },
  {
    id: 'static',
    name: 'STATIC CHARGE',
    rarity: 1,
    slot: 'aura',
    tags: ['crit'],
    desc: 'HITS ARC 15% TO ANOTHER FOE',
    icon: [
      '.C.....kkk.',
      '......kCik.',
      '.....kCik..',
      '....kCik...',
      '...kCiikkk.',
      '..kCCCCCik.',
      '..kkkkCik..',
      '.....kCk...',
      '....kCk..C.',
      '...kck.....',
      '...kk......',
    ],
    fx: (l) => ({ chain: 15 * l }),
  },
  {
    id: 'haggler',
    name: 'HAGGLER',
    rarity: 1,
    slot: 'aura',
    tags: ['scav'],
    desc: 'SHOPS 10% CHEAPER, 3% INTEREST',
    icon: [
      '...........',
      '..kkkkkkkk.',
      '.kyyyyyyyOk',
      'kykkyryyrOk',
      'kykkyyryyOk',
      '.kyyyryyyOk',
      '..kkkkkkkk.',
      '..l........',
      '.l...kkk...',
      '.l..kyOyk..',
      '.....kkk...',
    ],
    bonus: (b, l) => (b.discount += 0.1 * l),
    fx: (l) => ({ interest: 3 * l }),
  },
  {
    id: 'stink_cloud',
    name: 'STINK CLOUD',
    rarity: 2,
    slot: 'aura',
    tags: ['trash'],
    desc: 'FIGHTS START WITH 4 POISON ON ALL FOES',
    icon: [
      '...kkk.....',
      '..kLLLk.kk.',
      '.kLmLLLkLLk',
      'kLLLLGGLLGk',
      'kLGGLLGGGGk',
      '.kGGGGGGGk.',
      '..kkkkkkk..',
      '...G..G..G.',
      '..G..G..G..',
      '...G..G..G.',
      '...........',
    ],
    fx: (l) => ({ stink: 4 * l }),
  },
  {
    id: 'combo_fever',
    name: 'COMBO FEVER',
    rarity: 2,
    slot: 'aura',
    tags: ['speed'],
    desc: 'EVERY KILL GIVES +1 ACTION POINT',
    icon: [
      '.....kkkk..',
      '....kyyyk..',
      '...kyyyk...',
      '..kyyyk....',
      '.kyyyykkkk.',
      'kOOOyyyyyk.',
      '.kkkkOyyk..',
      '....kOyk...',
      '...kOyk....',
      '..kOk......',
      '..kk.......',
    ],
    fx: () => ({ killAp: 1 }),
  },
  {
    id: 'spirit_fox',
    name: 'SPIRIT FOX',
    rarity: 2,
    slot: 'aura',
    tags: ['speed', 'crit'],
    desc: '+8% DODGE, DODGES HIT BACK FOR 4',
    icon: [
      '.k.......k.',
      'kCk.....kCk',
      'kCik...kiCk',
      'kCiCkkkCiCk',
      'kCCCCCCCCCk',
      'kCbkCCCkbCk',
      'kCCCCCCCCCk',
      '.kCCCkCCCk.',
      '..kCCwCCk..',
      '...kkCkk...',
      '....k.k....',
    ],
    bonus: (b) => (b.dodge += 0.08),
    fx: (l) => ({ dodgeStrike: 4 * l }),
  },
  {
    id: 'rage_aura',
    name: 'CORNERED RAGE',
    rarity: 3,
    slot: 'aura',
    tags: ['crit', 'tank'],
    desc: 'UNDER 35% HEALTH: +60% DAMAGE',
    icon: [
      '.....k.....',
      '....krk....',
      '...krrk.k..',
      '..krork.kk.',
      '.krrookkrk.',
      '.kroyorrrk.',
      'krooyyoork.',
      'kroyywyork.',
      'kroyyyyork.',
      '.krooooork.',
      '..kkkkkkk..',
    ],
    fx: (l) => ({ rage: 60 * l }),
  },
  {
    id: 'trash_vortex',
    name: 'TRASH VORTEX',
    rarity: 4,
    slot: 'aura',
    tags: ['trash'],
    desc: 'POISON ALL 6 AT START, HIT ALL 6 EACH TURN',
    needsBoss: true,
    icon: [
      'kkkkkkkkkkk',
      'kLmLLLLGGGk',
      'rkkkkkkkkkO',
      '.kLLLLGGGk.',
      '..kkkkkkk.y',
      'O.kLLGGGk..',
      '...kkkkk...',
      '..rkLGGk.O.',
      '....kkk....',
      '....kGk....',
      '.....k.....',
    ],
    fx: (l) => ({ stink: 6 * l, boomerang: 6 * l }),
  },
];
