// Back slot: packs, capes and wings, anchored behind the shoulders (11,12).
// Packs are drawn behind the raccoon and peek out between the tail (x1-9) and the head (x15+).
// Wings rise above the tail. Capes and shells drape over the back in front.
import type { ItemDef } from '../types';
import { over, tint } from './art';

// A wing that rises up and back from the shoulders: tip top-left, root bottom-right.
const WING = [
  'kkkk...........',
  'kaaakkk........',
  'kabbaaakk......',
  '.kbbbbbaakk....',
  '.kbbbbbbbaak...',
  'kkbbbbbbbbbak..',
  'kbbbbbbbbbbbak.',
  '.kbbbbbbbbbbbak',
  'kkbbkbbbbbbbbak',
  'kbbk.kbbkbbbbak',
  '.kk...kk.kbbbak',
  '.........kbbbk.',
  '..........kbbk.',
  '..........kbk..',
  '...........k...',
];
const wing = (map: Record<string, string>, extra: string[] = []) => {
  const rows = WING.map((r, y) => [...r].map((ch, x) => (extra[y]?.[x] && extra[y][x] !== '.' ? extra[y][x] : (map[ch] ?? ch))).join(''));
  // flap: the alt frame dips the wing two pixels
  const alt = ['.'.repeat(15), '.'.repeat(15), ...rows.slice(0, -2)];
  return { anchor: 'back' as const, x: -11, y: -18, behind: true, rows, alt };
};

// A cape streaming up and back from the neck, over the top of the tail.
const CAPE = [
  'kkk...............',
  'kaakkk............',
  'kbaaaakkk.........',
  '.kbbaaaaakkk......',
  'kbbbbbaaaaaakkk...',
  'kbkkbbbbbaaaaaakk.',
  '.k..kkkbbbbbaaaaak',
  '.......kkkbbbbbaak',
  '..........kkkbbbbk',
  '.............kkkk.',
];
const CAPE_ALT = [
  '..................',
  'kkkk..............',
  'kaaakkk...........',
  'kbbaaaaakkk.......',
  '.kbbbbaaaaaakkk...',
  'kbbkbbbbbaaaaaakk.',
  'kk.kkkkbbbbbaaaaak',
  '.......kkkbbbbbaak',
  '..........kkkbbbbk',
  '.............kkkk.',
];
const cape = (a: string, b: string, top: string[] = [], topAlt: string[] = top) => ({
  anchor: 'back' as const,
  x: -12,
  y: -12,
  behind: true,
  rows: over(tint(CAPE, { a, b }), top),
  alt: over(tint(CAPE_ALT, { a, b }), topAlt),
});

export const ITEMS_BACK: ItemDef[] = [
  {
    id: 'backpack',
    name: 'BACKPACK',
    rarity: 0,
    slot: 'back',
    tags: ['scav'],
    desc: '+30% SHINIES',
    gear: [
      {
        anchor: 'back',
        x: -3,
        y: -11,
        behind: true,
        rows: [
          '..kkkk..',
          '.kLGGGk.',
          'kLGGGGGk',
          'kGGGGGFk',
          'kkkkkkkk',
          'kGDDDDGk',
          'kGDyyDGk',
          'kGDDDDFk',
          'kGGGGGFk',
          'kFFFFFFk',
          '.kkkkkk.',
        ],
      },
    ],
    bonus: (b, l) => (b.shinyMult += 0.3 * l),
  },
  {
    id: 'lid_shield',
    name: 'LID SHIELD',
    rarity: 0,
    slot: 'back',
    tags: ['tank', 'trash'],
    desc: '+2 DEF',
    gear: [
      {
        anchor: 'back',
        x: -5,
        y: -12,
        behind: true,
        rows: [
          '...kkkkk...',
          '..kwllllk..',
          '.kwlgggllk.',
          'kwlgkkkglgk',
          'klgkdddkggk',
          'klgkdddkggk',
          'klggkkkggdk',
          '.kgggggggk.',
          '..kggggdk..',
          '...kkkkk...',
        ],
      },
    ],
    bonus: (b, l) => (b.def += 2 * l),
  },
  {
    id: 'bindle',
    name: 'BINDLE',
    rarity: 0,
    slot: 'back',
    tags: ['scav'],
    desc: 'SHOPS 10% CHEAPER',
    gear: [
      {
        anchor: 'back',
        x: -11,
        y: -14,
        behind: true,
        rows: [
          '..kkkkk......',
          '.krrwrrk.....',
          'krwrrrwrk....',
          'krrrwrrRk....',
          '.kRrrRRkN....',
          '..kkkkk..N...',
          '..........N..',
          '...........N.',
          '............N',
          '............N',
        ],
      },
    ],
    bonus: (b, l) => (b.discount += 0.1 * l),
  },
  {
    id: 'hero_scarf',
    name: 'HERO SCARF',
    rarity: 0,
    slot: 'back',
    tags: ['crit', 'speed'],
    desc: '+1 STR, +1 AGI',
    gear: [cape('r', 'R', ['', '.P', '..PP', '....PPP', '......PPPP', '.........PPP'], ['', '', '.P', '..PPP', '.....PPPP', '.........PPP'])],
    bonus: (b, l) => {
      b.str += l;
      b.agi += l;
    },
  },
  {
    id: 'firework_pack',
    name: 'FIREWORK PACK',
    rarity: 1,
    slot: 'back',
    tags: ['trash'],
    desc: 'FIGHTS START: 4 DAMAGE TO ALL FOES',
    gear: [
      {
        anchor: 'back',
        x: -3,
        y: -14,
        behind: true,
        rows: [
          '........',
          '.k...k..',
          'krk.kbk.',
          'kwk.kwkk',
          'krkkkbkyk',
          'kwkrkwkyk',
          'krkwkbkOk',
          'kkkrkkkyk',
          'kNNNNNNNk',
          'knnnnnnNk',
          'knnnnnnNk',
          'kkkkkkkkk',
        ].map((r) => r.padEnd(9, '.')),
        alt: [
          '.y...o..',
          '.k...k..',
          'krk.kbk.',
          'kwk.kwkk',
          'krkkkbkyk',
          'kwkrkwkyk',
          'krkwkbkOk',
          'kkkrkkkyk',
          'kNNNNNNNk',
          'knnnnnnNk',
          'knnnnnnNk',
          'kkkkkkkkk',
        ].map((r) => r.padEnd(9, '.')),
      },
    ],
    fx: (l) => ({ firstStrike: 4 * l }),
  },
  {
    id: 'turtle_shell',
    name: 'TURTLE SHELL',
    rarity: 1,
    slot: 'back',
    tags: ['tank'],
    desc: '+2 DEF, GAIN 2 BLOCK WHEN HIT',
    gear: [
      {
        anchor: 'back',
        x: -4,
        y: -4,
        rows: [
          '....kkkkk....',
          '..kkzmzzzkk..',
          '.kzmzGGzGzzk.',
          'kzGzGGzGGzGzk',
          'kzzGzzGzzGzFk',
          'kSSSSSSSSSSSk',
          '.kkkkkkkkkkk.',
        ],
      },
    ],
    bonus: (b, l) => (b.def += 2 * l),
    fx: (l) => ({ hurtBlock: 2 * l }),
  },
  {
    id: 'bat_wings',
    name: 'BAT WINGS',
    rarity: 1,
    slot: 'back',
    tags: ['speed'],
    desc: '+5% DODGE, DODGES HIT BACK FOR 3',
    gear: [wing({ a: 'v', b: 'e' }, ['', '', '', '', '', '', '...u...u', '....u...u', '.....u...u'])],
    bonus: (b) => (b.dodge += 0.05),
    fx: (l) => ({ dodgeStrike: 3 * l }),
  },
  {
    id: 'treasure_sack',
    name: 'TREASURE SACK',
    rarity: 2,
    slot: 'back',
    tags: ['scav'],
    desc: 'SHOPS 15% CHEAPER, 10% INTEREST',
    gear: [
      {
        anchor: 'back',
        x: -3,
        y: -13,
        behind: true,
        rows: [
          '..kyk....',
          '.kyOyk...',
          '.kOywkk..',
          '..kkkyOk.',
          '..kNNkk..',
          '.knnnnk..',
          'knnTnnnk.',
          'knnOOnNk.',
          'knTOnnNk.',
          'knnOOnNk.',
          'kNnnnNNk.',
          '.kkkkkk..',
        ],
        alt: [
          '..kyk....',
          '.kyOyk...',
          '.kOyykk..',
          '..kkkwOk.',
          '..kNNkk..',
          '.knnnnk..',
          'knnTnnnk.',
          'knnOOnNk.',
          'knTOnnNk.',
          'knnOOnNk.',
          'kNnnnNNk.',
          '.kkkkkk..',
        ],
      },
    ],
    bonus: (b, l) => (b.discount += 0.15 * l),
    fx: (l) => ({ interest: 10 * l }),
  },
  {
    id: 'leaf_cape',
    name: 'LEAF CAPE',
    rarity: 2,
    slot: 'back',
    tags: ['speed'],
    desc: '+2 AGI, +10% DODGE',
    gear: [
      cape(
        'G',
        'F',
        ['', '.L', '..zL', '...L..zL', '..zL.L...zL', '..L...zL..L.zL', '........L.zL..L', '...........zL.L', '............L'],
        ['', '', '.L', '..zL..zL', '...L.L...zL', '..zL..zL..L.zL', '........L.zL..L', '...........zL.L', '............L'],
      ),
    ],
    bonus: (b, l) => {
      b.dodge += 0.1 * l;
      b.agi += 2;
    },
  },
  {
    id: 'beehive',
    name: 'BEEHIVE',
    rarity: 2,
    slot: 'back',
    tags: ['trash', 'scav'],
    desc: 'END OF TURN: BEES STING A FOE FOR 5',
    gear: [
      {
        anchor: 'back',
        x: -4,
        y: -13,
        behind: true,
        rows: [
          '....N......',
          '...kNk.....',
          '..kyyyk....',
          '.kyYyyOk...',
          '.kSSSSSk...',
          'kyyyyyyOk..',
          'kSSSSSSSk..',
          'kyyykyyOk..',
          'kSSkHkSSk..',
          '.kyyyyOk...',
          '..kkkkk....',
        ],
        alt: [
          '....N....y.',
          '...kNk..kHk',
          '..kyyyk.wy.',
          '.kyYyyOk...',
          '.kSSSSSk...',
          'kyyyyyyOk..',
          'kSSSSSSSk..',
          'kyyykyyOk..',
          'kSSkHkSSk..',
          '.kyyyyOk...',
          '..kkkkk....',
        ],
      },
    ],
    bonus: (b, l) => (b.shinyMult += 0.1 * l),
    fx: (l) => ({ flies: 5 * l }),
  },
  {
    id: 'jetpack',
    name: 'JETPACK',
    rarity: 3,
    slot: 'back',
    tags: ['speed'],
    desc: '+1 ACTION POINT EVERY TURN',
    gear: [
      {
        anchor: 'back',
        x: -4,
        y: -13,
        behind: true,
        rows: [
          '..kkk.kkk..',
          '.kwlgkwlgk.',
          '.klrgklrgk.',
          '.klrgklrgk.',
          '.klggklggk.',
          '.kkkkkkkkk.',
          '.klggOlggk.',
          '.klggOlggk.',
          '.klggklggk.',
          '..kdk.kdk..',
          '..yoy.yoy..',
          '...o...o...',
        ],
        alt: [
          '..kkk.kkk..',
          '.kwlgkwlgk.',
          '.klrgklrgk.',
          '.klrgklrgk.',
          '.klggklggk.',
          '.kkkkkkkkk.',
          '.klggOlggk.',
          '.klggOlggk.',
          '.klggklggk.',
          '..kdk.kdk..',
          '..oyo.oyo..',
          '..yoy.yoy..',
        ],
      },
      // exhaust flame that shows below the tail base
      { anchor: 'back', x: -3, y: -1, rows: ['.o.o.', 'oyoyo', '.o.o.'], alt: ['.y.y.', 'yoyoy', 'o.o.o'] },
    ],
    bonus: (b, l) => (b.ap += l),
  },
  {
    id: 'angel_wings',
    name: 'ANGEL WINGS',
    rarity: 3,
    slot: 'back',
    tags: ['tank', 'speed'],
    desc: 'HEAL 3 EVERY TURN, +5% DODGE',
    gear: [wing({ a: 'O', b: 'w' }, ['', '.y', '..wi', '...wwi', '..i..wwi', '...i..wi', '..i..i..wi', '...i..i..i', '....i..i..i', '.........i.i'])],
    bonus: (b) => (b.dodge += 0.05),
    fx: (l) => ({ regen: 3 * l }),
  },
  {
    id: 'comet_wings',
    name: 'COMET WINGS',
    rarity: 4,
    slot: 'back',
    tags: ['speed', 'crit'],
    desc: '+1 AP, +10% DODGE, DODGES HIT FOR 6',
    needsBoss: true,
    gear: [
      wing({ a: 'C', b: 'c' }, ['', '.y', '..Cw', '...bCC', '..b.y.CC', '...b..bCc', '..b..b..bC', '...b..y..b', '....b..b..b', '.........b.b', '..........b']),
      { anchor: 'back', x: -13, y: -17, behind: true, rows: ['y.....', '......', '..w...', '......', 'O....y'], alt: ['......', '..y...', '.....w', 'w...O.', '......'] },
    ],
    bonus: (b, l) => {
      b.ap += 1;
      b.dodge += 0.1;
    },
    fx: (l) => ({ dodgeStrike: 6 * l }),
  },
];
