// Body slot: shirts and armour, anchored on the middle of the torso (17,16).
// Most pieces start from the VEST shell in art.ts and paint details on top.
import type { ItemDef } from '../types';
import { VEST, VEST_X, VEST_Y, over, tint } from './art';

const vest = (a: string, b: string, c: string, top: string[] = [], alt?: string[]) => ({
  anchor: 'body' as const,
  x: VEST_X,
  y: VEST_Y,
  rows: over(tint(VEST, { a, b, c }), top),
  ...(alt ? { alt: over(tint(VEST, { a, b, c }), alt) } : {}),
});

export const ITEMS_BODY: ItemDef[] = [
  {
    id: 'cardboard',
    name: 'CARDBOARD ARMOR',
    rarity: 0,
    slot: 'body',
    tags: ['tank'],
    desc: '+2 VIT',
    gear: [
      vest('n', 'N', 'T', [
        '....................',
        '....................',
        '..........s.........',
        '..........s.........',
        '..N.......s.........',
        '...N......s....N....',
        '..........s...N.....',
        '..........s.........',
        '..........s.........',
      ]),
    ],
    bonus: (b, l) => (b.vit += 2 * l),
  },
  {
    id: 'hoodie',
    name: 'COMFY HOODIE',
    rarity: 0,
    slot: 'body',
    tags: ['speed', 'tank'],
    desc: '+1 AGI, +1 VIT',
    gear: [
      { anchor: 'body', x: -6, y: -9, behind: true, rows: ['..kkkk.', '.kLGGGk', 'kLGFFGk', 'kGFkkFk', 'kGFk.kk', 'kGGk...'] },
      vest('G', 'F', 'L', [
        '....................',
        '....................',
        '.............w......',
        '.............w.w....',
        '...............w....',
        '....................',
        '.......kkkkkkkk.....',
        '.......kFFFFFFk.....',
        '....................',
      ]),
    ],
    bonus: (b, l) => {
      b.agi += l;
      b.vit += l;
    },
  },
  {
    id: 'garbage_bag',
    name: 'GARBAGE BAG',
    rarity: 0,
    slot: 'body',
    tags: ['trash'],
    desc: '+1 DEF, +1 VIT',
    gear: [
      vest('d', 'H', 'g', [
        '..........kyk.......',
        '.........kyyyk......',
        '..........kyk.......',
        '....l.........l.....',
        '.....l.........l....',
        '..........l.........',
        '...........l........',
        '....................',
        '....................',
      ]),
    ],
    bonus: (b, l) => {
      b.def += l;
      b.vit += l;
    },
  },
  {
    id: 'hawaii_shirt',
    name: 'HAWAII SHIRT',
    rarity: 0,
    slot: 'body',
    tags: ['scav'],
    desc: '+20% SHINIES',
    gear: [
      vest('c', 'b', 'C', [
        '....................',
        '..........kk........',
        '.........kwwk.......',
        '.....h...kwwk..y....',
        '....hyh...kk..yhy...',
        '.....h...G.....y....',
        '........GLG.h.......',
        '...y.....G.hyh......',
        '..........y.h.......',
      ]),
    ],
    bonus: (b, l) => (b.shinyMult += 0.2 * l),
  },
  {
    id: 'burglar_tee',
    name: 'BURGLAR TEE',
    rarity: 0,
    slot: 'body',
    tags: ['crit'],
    desc: '+2 STR',
    gear: [
      vest('w', 'l', 'w', [
        '....................',
        '....................',
        '.....HHHHHHHHHHHH...',
        '....................',
        '..HHHHHHHHHHHHHHHHH.',
        '....................',
        '..HHHHHHHHHHHHHHHHH.',
        '....................',
        '...HHHHHHHHHHHHHHH..',
      ]),
    ],
    bonus: (b, l) => (b.str += 2 * l),
  },
  {
    id: 'puffer_vest',
    name: 'PUFFER VEST',
    rarity: 1,
    slot: 'body',
    tags: ['tank'],
    desc: '+1 VIT, GAIN 4 BLOCK WHEN HIT',
    gear: [
      vest('o', 'r', 'y', [
        '....................',
        '....................',
        '...........l........',
        '..........kl........',
        '..kkkkkkkkklkkkkkkk.',
        '..........kl........',
        '..........kl........',
        '..kkkkkkkkklkkkkkk..',
        '..........kl........',
      ]),
    ],
    bonus: (b) => (b.vit += 1),
    fx: (l) => ({ hurtBlock: 4 * l }),
  },
  {
    id: 'life_vest',
    name: 'LIFE VEST',
    rarity: 1,
    slot: 'body',
    tags: ['tank'],
    desc: '+2 VIT, HEAL 1 EVERY TURN',
    gear: [
      vest('o', 'q', 'y', [
        '....................',
        '....................',
        '....................',
        '....................',
        '..wwwwwwwwwwwwwwww..',
        '...........kk.......',
        '...........kk.......',
        '..wwwwwwwwwwwwwwwww.',
        '....................',
      ]),
    ],
    bonus: (b, l) => (b.vit += 2 * l),
    fx: (l) => ({ regen: l }),
  },
  {
    id: 'cap_mail',
    name: 'BOTTLECAP MAIL',
    rarity: 1,
    slot: 'body',
    tags: ['scav', 'tank'],
    desc: '+2 DEF, +15% SHINIES',
    gear: [
      vest('l', 'g', 'w', [
        '....................',
        '....................',
        '.....O..r..O..r..O..',
        '...r..O..r..O..r....',
        '..O..r..O..r..O..r..',
        '...r..O..r..O..r..O.',
        '..O..r..O..r..O..r..',
        '...r..O..r..O..r....',
        '....................',
      ]),
    ],
    bonus: (b, l) => {
      b.def += 2 * l;
      b.shinyMult += 0.15 * l;
    },
  },
  {
    id: 'tracksuit',
    name: 'TRACKSUIT',
    rarity: 1,
    slot: 'body',
    tags: ['speed'],
    desc: '+3 AGI, +5% DODGE',
    gear: [
      vest('r', 'R', 'P', [
        '....................',
        '.............kkk....',
        '.............kwk....',
        '..ww..........l.....',
        '...ww.........l.....',
        '....ww........l.....',
        '.....ww.......l.....',
        '......ww......l.....',
        '....................',
      ]),
    ],
    bonus: (b, l) => {
      b.agi += 3 * l;
      b.dodge += 0.05;
    },
  },
  {
    id: 'spiked_jacket',
    name: 'SPIKED JACKET',
    rarity: 2,
    slot: 'body',
    tags: ['tank'],
    desc: '+1 DEF, ATTACKERS TAKE 4 DAMAGE',
    gear: [
      vest('d', 'H', 'g', [
        '.....w..w..w..w.....',
        '.....l..l..l..l.....',
        '....................',
        '....l..l......l..l..',
        '...l.....l..l.....l.',
        '....................',
        '....l..l......l..l..',
        '...l.....l..l.....l.',
        '....................',
      ]),
    ],
    bonus: (b) => (b.def += 1),
    fx: (l) => ({ thorns: 4 * l }),
  },
  {
    id: 'tin_can_armor',
    name: 'TIN CAN ARMOR',
    rarity: 2,
    slot: 'body',
    tags: ['tank', 'trash'],
    desc: '+1 DEF, 3 BLOCK AT THE START OF EVERY TURN',
    gear: [
      vest('l', 'g', 'w', [
        '....................',
        '....................',
        '.....g..g..g..g..g..',
        '....................',
        '..rrrrrrrrrrrrrrrrr.',
        '..rrrwwwrrrrryyrrrr.',
        '..rrrrrrrrrrrrrrrrr.',
        '....................',
        '.....g..g..g..g..g..',
      ]),
    ],
    bonus: (b, l) => (b.def += l),
    fx: (l) => ({ startBlock: 3 * l }),
  },
  {
    id: 'ninja_gi',
    name: 'NINJA GI',
    rarity: 2,
    slot: 'body',
    tags: ['speed', 'crit'],
    desc: '+5% DODGE, DODGES HIT BACK FOR 4',
    gear: [
      vest('I', 'H', 'B', [
        '....................',
        '.........kkkkk......',
        '..........wkw.......',
        '...........w........',
        '....................',
        '..rrrrrrrrrrrrrrrrr.',
        '..RRRRRRRrrRRRRRRRR.',
        '........r..r........',
        '.......r....r.......',
      ]),
    ],
    bonus: (b) => (b.dodge += 0.05),
    fx: (l) => ({ dodgeStrike: 4 * l }),
  },
  {
    id: 'royal_armor',
    name: 'ROYAL ARMOR',
    rarity: 3,
    slot: 'body',
    tags: ['tank'],
    desc: 'HEAL 2 EVERY TURN, GAIN 3 BLOCK WHEN HIT',
    gear: [
      { anchor: 'body', x: -12, y: -6, behind: true, rows: ['..kkkk..', '.kvvvvk.', 'kvvvevk.', 'kvvveek.', 'kvveeek.', 'kveeeek.', '.kkkkk..'] },
      vest(
        'O',
        'S',
        'y',
        [
          '....................',
          '.....kkkkkkkkkkkk...',
          '...kkvvvvvvvvvvvkk..',
          '..kvvvYyyyyyyvvvvk..',
          '..kSSSyyyrryyySSSk..',
          '..kSSSyyrhrryySSSk..',
          '..kSSSyyyrryyySSSk..',
          '...kSSSSyyyySSSSk...',
          '....................',
        ],
        [
          '....................',
          '.....kkkkkkkkkkkk...',
          '...kkvvvvvvvvvvvkk..',
          '..kvvvYyyyyyyvvvvk..',
          '..kSSSyyyrryyySSSk..',
          '..kSSSyyrwrryySSSk..',
          '..kSSSyyyrryyySSSk..',
          '...kSSSSyyyySSSSk...',
          '....................',
        ],
      ),
    ],
    bonus: (b) => (b.def += 1),
    fx: (l) => ({ regen: 2 * l, hurtBlock: 3 * l }),
  },
  {
    id: 'trash_mech',
    name: 'TRASH MECH',
    rarity: 4,
    slot: 'body',
    tags: ['tank', 'trash'],
    desc: '+3 DEF, +3 VIT, 6 BLOCK EVERY TURN',
    needsBoss: true,
    gear: [
      // exhaust stacks behind the shoulders
      {
        anchor: 'body',
        x: -8,
        y: -11,
        behind: true,
        rows: ['.o..o.', 'kkk.kkk', 'kgk.kgk', 'kgk.kgk', 'kgk.kgk', 'kgk.kgk'].map((r) => r.padEnd(7, '.')),
        alt: ['o.y.o..', 'kkkokkk', 'kgk.kgk', 'kgk.kgk', 'kgk.kgk', 'kgk.kgk'],
      },
      vest(
        'l',
        'g',
        'w',
        [
          '....kkkkkkkkkkkkk...',
          '...kOOOOOOOOOOOOOk..',
          '..kOkkkkkkkkkkkkkOk.',
          '..kgdlllkkkklllldgk.',
          '.kgldlllkCCklllldgk',
          '.kglldllkCtklllldgk',
          '.kglldllkkkklllldgk',
          '.kgglldyldrlldGlggk',
          '..kOOOOOOOOOOOOOOk..',
        ].map((r) => r.padEnd(20, '.')),
        [
          '....kkkkkkkkkkkkk...',
          '...kOOOOOOOOOOOOOk..',
          '..kOkkkkkkkkkkkkkOk.',
          '..kgdlllkkkklllldgk.',
          '.kgldlllktCklllldgk',
          '.kglldllkCCklllldgk',
          '.kglldllkkkklllldgk',
          '.kgglldGldyllldrlggk',
          '..kOOOOOOOOOOOOOOk..',
        ].map((r) => r.padEnd(20, '.')),
      ),
    ],
    bonus: (b, l) => {
      b.def += 3 * l;
      b.vit += 3 * l;
    },
    fx: (l) => ({ startBlock: 6 * l }),
  },
];
