// Paw slot: things the raccoon holds, anchored on the front paw (27,17).
// Held items stand in front of the chest with their grip at the paw; long ones lean
// forward so they clear the snout (x26-34, y8-11).
import type { ItemDef } from '../types';

export const ITEMS_PAW: ItemDef[] = [
  {
    id: 'slingshot',
    name: 'SLINGSHOT',
    rarity: 0,
    slot: 'paw',
    tags: ['crit'],
    desc: '+1 STR, +1 LCK',
    gear: [
      {
        anchor: 'paw',
        x: 1,
        y: -6,
        rows: [
          'k...k..',
          'nk.kNk.',
          'nkrkNk.',
          'knnNk..',
          '.knk...',
          '.knk...',
          '.kNk...',
          '..k....',
        ].map((r) => r),
      },
    ],
    bonus: (b, l) => {
      b.str += l;
      b.lck += l;
    },
  },
  {
    id: 'big_stick',
    name: 'BIG STICK',
    rarity: 0,
    slot: 'paw',
    tags: ['trash'],
    desc: '+2 STR',
    gear: [
      {
        anchor: 'paw',
        x: 0,
        y: -8,
        rows: [
          '.....kk.',
          '....kLGk',
          '...knkk.',
          '...knk..',
          '..knk...',
          '..knk...',
          '.knk....',
          '.kNk....',
          'kNk.....',
          '.k......',
        ],
      },
    ],
    bonus: (b, l) => (b.str += 2 * l),
  },
  {
    id: 'plunger',
    name: 'PLUNGER',
    rarity: 0,
    slot: 'paw',
    tags: ['trash', 'tank'],
    desc: '+1 STR, +1 DEF',
    gear: [
      {
        anchor: 'paw',
        x: 1,
        y: -8,
        rows: [
          '.kkkkk.',
          'krPrrRk',
          'kRRRRRk',
          '.kkkkk.',
          '..knk..',
          '..knk..',
          '..knk..',
          '..knk..',
          '..kNk..',
          '...k...',
        ],
      },
    ],
    bonus: (b, l) => {
      b.str += l;
      b.def += l;
    },
  },
  {
    id: 'lollipop',
    name: 'GIANT LOLLIPOP',
    rarity: 0,
    slot: 'paw',
    tags: ['tank'],
    desc: '+2 VIT',
    gear: [
      {
        anchor: 'paw',
        x: 1,
        y: -9,
        rows: [
          '..kkk..',
          '.khwhk.',
          'khwwwhk',
          'kwhhhwk',
          'khwwhMk',
          '.khMMk.',
          '..kkk..',
          '..kwk..',
          '..kwk..',
          '..kwk..',
          '...k...',
        ],
      },
    ],
    bonus: (b, l) => (b.vit += 2 * l),
  },
  {
    id: 'toothbrush',
    name: 'TOOTHBRUSH',
    rarity: 0,
    slot: 'paw',
    tags: ['speed'],
    desc: '+1 STR, +1 AGI',
    gear: [
      {
        anchor: 'paw',
        x: 1,
        y: -8,
        rows: [
          '.kkk.',
          'kwiwk',
          'kiwik',
          'kcbck',
          '.kbk.',
          '.kck.',
          '.kbk.',
          '.kbk.',
          '.kBk.',
          '..k..',
        ],
      },
    ],
    bonus: (b, l) => {
      b.str += l;
      b.agi += l;
    },
  },
  {
    id: 'bottle_rocket',
    name: 'BOTTLE ROCKETS',
    rarity: 1,
    slot: 'paw',
    tags: ['trash'],
    desc: 'SINGLE HITS SPLASH 30% TO OTHER FOES',
    gear: [
      {
        anchor: 'paw',
        x: 1,
        y: -9,
        rows: [
          '...k...',
          '..krk..',
          '..kwk..',
          '..krk..',
          '.kkGkk.',
          '.kGLGk.',
          'kGGLGGk',
          'kGGLGFk',
          'kGGGGFk',
          'kFGGGFk',
          '.kkkkk.',
        ],
        alt: [
          '...y...',
          '..krk..',
          '..kwk..',
          '..krk..',
          '.kkGkk.',
          '.kGLGk.',
          'kGGLGGk',
          'kGGLGFk',
          'kGGGGFk',
          'kFGGGFk',
          '.kkkkk.',
        ],
      },
    ],
    fx: (l) => ({ splash: 30 * l }),
  },
  {
    id: 'baseball_bat',
    name: 'BASEBALL BAT',
    rarity: 1,
    slot: 'paw',
    tags: ['crit'],
    desc: '+2 STR, CRITS DEAL 25% MORE',
    gear: [
      {
        anchor: 'paw',
        x: 0,
        y: -8,
        rows: [
          '.......kk.',
          '......kTsk',
          '.....kTsSk',
          '....kTsSk.',
          '...kTsSk..',
          '..kTSkk...',
          '.kTSk.....',
          'kRSk......',
          'kRk.......',
          'kk........',
        ],
      },
    ],
    bonus: (b, l) => {
      b.str += 2 * l;
      b.critMult += 0.25 * l;
    },
  },
  {
    id: 'frying_pan',
    name: 'FRYING PAN',
    rarity: 1,
    slot: 'paw',
    tags: ['tank'],
    desc: '+1 STR, 2 BLOCK AT THE START OF EVERY TURN',
    gear: [
      {
        anchor: 'paw',
        x: 1,
        y: -6,
        rows: [
          '..kkkkk..',
          '.kgaaaak.',
          'kgadddaak',
          'kaddddddk',
          'kaddddddk',
          'kaaddddak',
          '.kaaaaak.',
          '..kkkkk..',
          '....kNk..',
          '....kNk..',
          '....kkk..',
        ],
      },
    ],
    bonus: (b, l) => (b.str += l),
    fx: (l) => ({ startBlock: 2 * l }),
  },
  {
    id: 'water_pistol',
    name: 'WATER PISTOL',
    rarity: 1,
    slot: 'paw',
    tags: ['speed'],
    desc: '+1 AGI, FIGHTS START: 3 DMG TO ALL',
    gear: [
      {
        anchor: 'paw',
        x: 0,
        y: -5,
        rows: [
          '..kkk......',
          '.koyok.....',
          'kkkkkkkkkk.',
          'kcCccccccbk',
          'kcbbbbkkkk.',
          'kcbk.k.....',
          'kbbk.......',
          'kbBk.......',
          '.kk........',
        ],
        alt: [
          '..kkk......',
          '.koyok.....',
          'kkkkkkkkkk.',
          'kcCccccccbkC',
          'kcbbbbkkkk.c',
          'kcbk.k.....',
          'kbbk.......',
          'kbBk.......',
          '.kk........',
        ].map((r) => r.slice(0, 11)),
      },
    ],
    bonus: (b, l) => (b.agi += l),
    fx: (l) => ({ firstStrike: 3 * l }),
  },
  {
    id: 'tiki_torch',
    name: 'TIKI TORCH',
    rarity: 2,
    slot: 'paw',
    tags: ['trash'],
    desc: '+1 STR, KILLS DEAL 5 TO ALL OTHER FOES',
    gear: [
      {
        anchor: 'paw',
        x: 1,
        y: -11,
        rows: [
          '...y...',
          '..yoy..',
          '.yoqoy.',
          '.oqYqo.',
          '.kqYqk.',
          'kSSSSSk',
          'kSNSNSk',
          '.kSSSk.',
          '..knk..',
          '..knk..',
          '..knk..',
          '..kNk..',
          '...k...',
        ],
        alt: [
          '..y....',
          '..oy.y.',
          '.yoqoo.',
          '.oqYqo.',
          '.kqYqk.',
          'kSSSSSk',
          'kSNSNSk',
          '.kSSSk.',
          '..knk..',
          '..knk..',
          '..knk..',
          '..kNk..',
          '...k...',
        ],
      },
    ],
    bonus: (b, l) => (b.str += l),
    fx: (l) => ({ killBurst: 5 * l }),
  },
  {
    id: 'golf_club',
    name: 'GOLF CLUB',
    rarity: 2,
    slot: 'paw',
    tags: ['crit'],
    desc: '+1 STR, CRITS KILL FOES UNDER 10% HP',
    gear: [
      {
        anchor: 'paw',
        x: 0,
        y: -2,
        rows: [
          'kk......',
          'krk.....',
          '.krk....',
          '..kwk...',
          '...kwk..',
          '....kwk.',
          '.....kwk',
          '...kkwlk',
          '..kwllgk',
          '...kkkk.',
        ],
      },
    ],
    bonus: (b, l) => (b.str += l),
    fx: (l) => ({ execute: 10 * l }),
  },
  {
    id: 'boomerang_lid',
    name: 'BOOMERANG LID',
    rarity: 3,
    slot: 'paw',
    tags: ['trash'],
    desc: 'END OF YOUR TURN: HIT ALL FOES FOR 5',
    gear: [
      {
        anchor: 'paw',
        x: 1,
        y: -5,
        rows: [
          '...kkkkk...',
          '.kkwwllOkk.',
          'kOwllkkllOk',
          'kOlllkkllOk',
          '.kkOOOOOkk.',
          '...kkkkk...',
          '....knk....',
          '....kNk....',
          '.....k.....',
        ],
        alt: [
          'C..kkkkk...',
          '.kkllwwOkk.',
          'kOllwkkllOk',
          'kOlllkkwlOk',
          '.kkOOOOOkkC',
          '...kkkkk...',
          '....knk....',
          '....kNk....',
          '.....k.....',
        ],
      },
    ],
    fx: (l) => ({ boomerang: 5 * l }),
  },
  {
    id: 'glow_sword',
    name: 'GLOW SWORD',
    rarity: 3,
    slot: 'paw',
    tags: ['crit', 'speed'],
    desc: '+3 STR, EVERY KILL GIVES +1 AP',
    gear: [
      {
        anchor: 'paw',
        x: 0,
        y: -10,
        rows: [
          '.........kk',
          '........kik',
          '.......kiCk',
          '......kiCk.',
          '.....kiCk..',
          '....kiCk...',
          '.k.kiCk....',
          'kOkiCk.....',
          '.kOOk......',
          '.kNOOk.....',
          'kNk.kOk....',
          'kk...k.....',
        ],
        alt: [
          '.........kk',
          '........kwk',
          '.......kwtk',
          '......kitk.',
          '.....kwtk..',
          '....kitk...',
          '.k.kwtk....',
          'kOkitk.....',
          '.kOOk......',
          '.kNOOk.....',
          'kNk.kOk....',
          'kk...k.....',
        ],
      },
    ],
    bonus: (b, l) => (b.str += 3 * l),
    fx: () => ({ killAp: 1 }),
  },
  {
    id: 'electric_fork',
    name: 'ELECTRIC FORK',
    rarity: 4,
    slot: 'paw',
    tags: ['crit'],
    desc: 'HITS ARC TO ANOTHER FOE FOR 70%',
    needsBoss: true,
    gear: [
      {
        anchor: 'paw',
        x: 1,
        y: -13,
        rows: [
          '..........',
          '.k.k.k....',
          'kwkwkwk...',
          'kwkwkwk...',
          'kwkwkwk...',
          'kwwlwwk...',
          '.kllgk....',
          '..klk.....',
          '..kOk.....',
          '..kyk.....',
          '..kOk.....',
          '..kyk.....',
          '..kOk.....',
          '...k......',
        ],
        alt: [
          'C...y.....',
          '.kCk.kC...',
          'kwkwkwk.y.',
          'kCkwkCkC..',
          'kwkwkwk...',
          'kwwCwwk.C.',
          'ykllgk....',
          '..klk.....',
          '..kOk.....',
          '..kyk.....',
          '..kOk.....',
          '..kyk.....',
          '..kOk.....',
          '...k......',
        ],
      },
    ],
    fx: (l) => ({ chain: 70 * l }),
  },
];
