// Every skill: the 18 originals plus new ones. Icons are 11x11 with a 'k' outline.
import type { SkillDef } from './types';

const pct = (n: number) => `${Math.round(n * 100)}%`;

const I = {
  claw: [
    '.k...k...k.',
    'kwk.kwk.kwk',
    'kwk.kwk.kwk',
    '.kwk.kwk.kw',
    '.kwk.kwk.kw',
    '..kwk.kwk.k',
    '..kwk.kwk..',
    '...kwk.kwk.',
    '...klk.klk.',
    '....k...k..',
    '...........',
  ],
  pounce: [
    '.....k.....',
    '....kok....',
    '.k.koyok.k.',
    '.kkoyyyokk.',
    '.koyywyyok.',
    'koyywwwyyok',
    '.koyywyyok.',
    '.kkoyyyokk.',
    '.k.koyok.k.',
    '....kok....',
    '.....k.....',
  ],
  guard: [
    '.kkkkkkkkk.',
    'kwwllllllgk',
    'kwllllllgdk',
    'kwllbbbllgk',
    'kllbbcbbldk',
    'kllbcbbbldk',
    '.klbbbblgk.',
    '.kllbblgdk.',
    '..klllldk..',
    '...kllgk...',
    '....kkk....',
  ],
  sweep: [
    '...........',
    '.......kkk.',
    '.....kkwwlk',
    '...kkwlllk.',
    '..kwllkkk..',
    '.kwlk......',
    'kwlk.......',
    'kwlk...k.k.',
    'kwllk..kwk.',
    '.kwllkkwlk.',
    '..kkkkkkk..',
  ],
  stink: [
    '......k.y..',
    '.....kNk.o.',
    '....kkNkk..',
    '..kkLLLLkk.',
    '.kLmLLGGGGk',
    '.kLmLGGGGGk',
    'kLLLGGGGGFk',
    'kLLGGGGGGFk',
    '.kGGGGGGFk.',
    '.kkGGGFFkk.',
    '...kkkkk...',
  ],
  trick: [
    '...kkkkk...',
    '..kyyyyyk..',
    '.kyYwyyyOk.',
    'kyYyyOOyyOk',
    'kyyyOyyyyOk',
    'kyyyyOOyyOk',
    'kyyyyyyOyOk',
    '.kyyOOOyOk.',
    '..kOOOOOk..',
    '...kkkkk.w.',
    'w.......w.w',
  ],
  snack: [
    'kkkkkkkkkkk',
    'kSSSSSSSSSk',
    '.kyyryyyyk.',
    '.kyyyyryyk.',
    '..kryyyyk..',
    '..kyyyryk..',
    '...kyyyk...',
    '...kyryk...',
    '....kyk....',
    '....kyk....',
    '.....k.....',
  ],
  frenzy: [
    '.kkk...kkk.',
    'krrrk.krrrk',
    'krPrrkrrrRk',
    'krrrrkkyRRk',
    'krrrrkyRRRk',
    '.krrkyyykk.',
    '..kkyyyk...',
    '...kkyk....',
    '....kyk....',
    '....kk.....',
    '...........',
  ],
  jeer: [
    '...kkkkk...',
    '..kyyyyyk..',
    '.kyyyyyyyk.',
    'kyykyyykyyk',
    'kyykyyykyyk',
    'kyyyyyyyyyk',
    'kykkkkkkkyk',
    'kyykPPPkyyk',
    '.kyykPkyyk.',
    '..kyykyyk..',
    '...kkkkk...',
  ],
  sniff: [
    '..kkkkk....',
    '.klllllk...',
    'klCiiiClk..',
    'klicCCCCk..',
    'klCCCCCCk..',
    'klCCCCClk..',
    '.klCCCllk..',
    '..kkkkkNNk.',
    '.......kNNk',
    '........kNk',
    '.........k.',
  ],
  lucky: [
    '..kkk.kkk..',
    '.kGLGkGLGk.',
    '.kGGGkGGGk.',
    'kkkGGkGGkkk',
    'kLGGGGGGGGk',
    'kGGGGGGGGFk',
    'kkkGGkGGkkk',
    '.kGGGkGGFk.',
    '.kGGFkkFFk.',
    '..kkkkFkkk.',
    '......kk...',
  ],
  flurry: [
    'k..k..k....',
    'wk.wk.wk...',
    '.wk.wk.wk..',
    '..k..k..k..',
    '...........',
    '....k..k..k',
    '....wk.wk.w',
    '.....wk.wk.',
    '......k..k.',
    '..k.......k',
    '..wk.......',
  ],
  spikes: [
    '.w..w..w..w',
    '.l..l..l..l',
    'kkkkkkkkkkk',
    'klllllllllk',
    'kldddddddgk',
    'kldwdddwdgk',
    'kldddddddgk',
    'kldwdddwdgk',
    'kgdddddddgk',
    'kkkkkkkkkkk',
    '.w..w..w..w',
  ],
  bash: [
    '...kkkkk...',
    '.kkwwlllkk.',
    'kwwllllllgk',
    'kwllkkklllk',
    'kllkdddkllk',
    'kllkdddklgk',
    'kllgkkkglgk',
    'klllllllggk',
    '.kkgggggkk.',
    '...kkkkk...',
    '...........',
  ],
  storm: [
    '..kkkkkkk..',
    '.kllllllgk.',
    '..kkkkkkk..',
    'r..kllgk..y',
    '...kkkkk...',
    '.y..klgk...',
    '....kkk..G.',
    '.....kgk...',
    '..G..kkk...',
    '......kk.r.',
    '.......k...',
  ],
  berserk: [
    'kk.......kk',
    'kwk.....kwk',
    '.kwk...kwk.',
    '..krkkkrk..',
    '.krrrrrrrk.',
    'krrkrrrkrrk',
    'krkykrkykrk',
    'krrrrrrrrRk',
    '.krkwkwkRk.',
    '..kkkkkkk..',
    '...........',
  ],
  dumpster: [
    '.kkkkkkkkk.',
    'kGLLLLLLLGk',
    'kkkkkkkkkkk',
    '.kGDGGGDGk.',
    '.kGDGGGDGk.',
    '.kGDGGGDGk.',
    '.kGDGGGDGk.',
    '.kGGGGGGGk.',
    '.kkkkkkkkk.',
    '..kk...kk..',
    '...........',
  ],
  sludge: [
    '...kkkkk...',
    '..kGGGGGk..',
    '.kGLmGGGGk.',
    'kGLmGGGGGGk',
    'kGGGGGGLGGk',
    'kGGGGGGGGFk',
    'kGGLGGGGGFk',
    '.kGGGGGGFk.',
    '..kFGkGFk..',
    '...kGkkk...',
    '....k......',
  ],
  // ---- new
  quickjab: [
    '...........',
    '.....kkkkk.',
    '....kwlwlwk',
    'l..kwlllllk',
    '...klllkkkk',
    'll.klllllgk',
    '...klllkkkk',
    'l..kllllggk',
    '....kgggkk.',
    '.....kkkk..',
    '...........',
  ],
  doubletap: [
    'kk.kk......',
    'kwkwk......',
    'kk.kk......',
    '.kkk.......',
    'kwwwk......',
    '.kkk.kk.kk.',
    '.....kwkwk.',
    '.....kk.kk.',
    '......kkk..',
    '.....kwwwk.',
    '......kkk..',
  ],
  headbutt: [
    '.y.....y...',
    'yYy...yYy..',
    '.y.kkkkky..',
    '..kllllllk.',
    '.kllllllllk',
    '.klgkllkglk',
    '.kllllllllk',
    '.klllkklllk',
    '..kllllllk.',
    '...kkkkkk..',
    '...........',
  ],
  bodyslam: [
    '....kkk....',
    '....kwk....',
    '....kwk....',
    '..kkkwkkk..',
    '...kwwwk...',
    '....kwk....',
    '.....k.....',
    '.o.......o.',
    'kkkkkkkkkkk',
    'klllllllllk',
    'kkkkkkkkkkk',
  ],
  snipe: [
    '....krk....',
    '..kkkrkkk..',
    '.kk..r..kk.',
    '.k...r...k.',
    'kk.......kk',
    'rrrr.r.rrrr',
    'kk.......kk',
    '.k...r...k.',
    '.kk..r..kk.',
    '..kkkrkkk..',
    '....krk....',
  ],
  reckless: [
    '.........kk',
    '........kwk',
    '.......kwlk',
    '......kwlk.',
    '.....kwlk..',
    '.k..kwlk...',
    'krkkwlk..r.',
    '.krrlk...r.',
    '..kRk...rr.',
    '.kRkRk..r..',
    'kRk.kk.....',
  ],
  toxicbite: [
    'kkkkkkkkkkk',
    'kRRRRRRRRRk',
    'kwwkwkkwwkk',
    '.kwk.k.kwk.',
    '.kwk...kwk.',
    '..k.....k..',
    '..L.....L..',
    '..G.....G..',
    '..k....kGk.',
    '.kGk...kGk.',
    '..k.....k..',
  ],
  cantoss: [
    '...........',
    '......kkkk.',
    '.l...kwlggk',
    '..l.kwkkkgk',
    '.l..krrrrrk',
    'l...kwwwwrk',
    '.l..krrrrRk',
    '..l.kwkkkgk',
    '.....kgggk.',
    '......kkk..',
    '...........',
  ],
  whirlwind: [
    '.kkkkkkkkk.',
    'kwwwlllllgk',
    '.kkkkkkkkk.',
    '..kwwllgk..',
    '..kkkkkkk..',
    '...kwllk...',
    '...kkkkk...',
    '....kwlk...',
    '....kkk....',
    '...kwk.....',
    '...kk......',
  ],
  curlup: [
    '...kkkkk...',
    '..kllllgk..',
    '.klddddlgk.',
    'kldlllldgk.',
    'kldlddldlgk',
    'kldldlldlgk',
    'kldlddddlgk',
    'klldlllllgk',
    '.klldddlgk.',
    '..kggggggk.',
    '...kkkkk...',
  ],
  playdead: [
    '...kkkkk...',
    '..kllllgk..',
    '.klllllllk.',
    '.klkklkklk.',
    '.kllklkllk.',
    '.klkklkklk.',
    '.klllllllk.',
    '.klllllllk.',
    '.klllllllk.',
    'kkkkkkkkkkk',
    'kGzGGzGGzGk',
  ],
  lickwounds: [
    '....kkk....',
    '...kwwwk...',
    '..kwkrkwk..',
    '.kwwkrkwwk.',
    'kwkkkrkkkwk',
    'kwrrrrrrrwk',
    'kwkkkrkkkwk',
    '.kwwkrkwwk.',
    '..kwkrkwk..',
    '...kwwwk...',
    '....kkk....',
  ],
  sugarrush: [
    '...........',
    'k.k.....k.k',
    'khkkkkkkkhk',
    'kPhkhwhhkhk',
    'kPPkwhhwkPk',
    'kPhkhhwhkhk',
    'khkkkkkkkhk',
    'k.k.....k.k',
    '...........',
    '..y..y..y..',
    '...........',
  ],
  burp: [
    '..kkk......',
    '.kmLLk.kk..',
    'kmLLLLkLLk.',
    'kLLLLLLLLLk',
    'kLLkkkkLLGk',
    'kLLkGGGkLGk',
    'kLLkkkkLGGk',
    'kLLkGGGkGGk',
    'kLLkkkkGGGk',
    '.kGGGGGGGk.',
    '..kkkkkkk..',
  ],
  howl: [
    '....kkkk...',
    '...kYYYYk..',
    '..kYYkkk...',
    '..kYk......',
    '..kYk..l.l.',
    '..kYYk..l.l',
    '...kYYkk.l.',
    '....kkkk...',
    '.l.l.......',
    'l.l.l......',
    '.l.l.......',
  ],
  shrapnel: [
    'l....k....l',
    '.l..klk..l.',
    '..kkkkkkk..',
    '.kddgggddk.',
    'kkdgkqkgdkk',
    'kldgqyqgdlk',
    'kkdgkqkgdkk',
    '.kddgggddk.',
    '..kkkkkkk..',
    '.l..klk..l.',
    'l....k....l',
  ],
  comet: [
    '.y.........',
    '..o.y......',
    'y..o.o.....',
    '.o..q.o....',
    '..o..qqkkk.',
    '...qqkoyyOk',
    '.....koywyOk',
    '.....koyyyOk',
    '......kOOOk',
    '.......kkk.',
    '...........',
  ].map((r) => r.padEnd(11, '.').slice(0, 11)),
  thunder: [
    '..kkkk.....',
    '.kllllkkk..',
    'klwlllllgk.',
    'klllllllldk',
    'kdddddddddk',
    '.kkkkykkkk.',
    '....kyk....',
    '...kyyk....',
    '...kkyyk...',
    '....kyk....',
    '....kk.....',
  ],
};

export const SKILLS: SkillDef[] = [
  // ---- the originals (same ids and mechanics)
  { id: 'claw', name: 'CLAW', desc: (l) => `HIT A FOE FOR ${pct(0.9 + 0.15 * l)}`, icon: I.claw, cost: 1, cooldown: 0, target: 'one', max: 3, effect: (l) => ({ dmg: 0.9 + 0.15 * l }) },
  { id: 'pounce', name: 'POUNCE', desc: (l) => `HUGE HIT FOR ${pct(1.8 + 0.4 * l)}`, icon: I.pounce, cost: 2, cooldown: 1, target: 'one', max: 3, effect: (l) => ({ dmg: 1.8 + 0.4 * l }) },
  { id: 'guard', name: 'GUARD', desc: (l) => `GAIN ${4 + 3 * l} BLOCK + DEF X2`, icon: I.guard, cost: 1, cooldown: 0, target: 'self', max: 3, effect: (l) => ({ block: 4 + 3 * l }) },
  { id: 'sweep', name: 'TAIL SWEEP', desc: (l) => `HIT ALL FOES FOR ${pct(0.6 + 0.2 * l)}`, icon: I.sweep, cost: 2, cooldown: 0, target: 'all', max: 3, effect: (l) => ({ dmg: 0.6 + 0.2 * l }) },
  { id: 'stink', name: 'STINK BOMB', desc: (l) => `POISON ALL FOES ${2 + 2 * l}`, icon: I.stink, cost: 1, cooldown: 2, target: 'all', max: 3, effect: (l) => ({ apply: { poison: 2 + 2 * l } }) },
  { id: 'trick', name: 'SHINY TRICK', desc: (l) => (l < 3 ? 'STUN A FOE FOR 1 TURN' : 'STUN A FOE, NO COOLDOWN'), icon: I.trick, cost: 1, cooldown: 3, target: 'one', max: 3, effect: () => ({ apply: { stun: 1 } }) },
  { id: 'snack', name: 'SNACK', desc: (l) => `HEAL ${15 + 10 * l}% HEALTH`, icon: I.snack, cost: 1, cooldown: 3, target: 'self', max: 3, effect: (l) => ({ heal: 0.15 + 0.1 * l }) },
  { id: 'frenzy', name: 'FRENZY', desc: (l) => `+${1 + l} AP, LOSE 4 HEALTH`, icon: I.frenzy, cost: 0, cooldown: 2, target: 'self', max: 2, effect: (l) => ({ ap: 1 + l, hpCost: 4 }) },
  { id: 'jeer', name: 'JEER', desc: (l) => `WEAKEN ALL FOES ${1 + l} TURNS`, icon: I.jeer, cost: 1, cooldown: 2, target: 'all', max: 3, effect: (l) => ({ apply: { weak: 1 + l } }) },
  { id: 'sniff', name: 'SNIFF OUT', desc: (l) => `FOE TAKES +50% FOR ${1 + l} TURNS`, icon: I.sniff, cost: 0, cooldown: 2, target: 'one', max: 3, effect: (l) => ({ apply: { vuln: 1 + l } }) },
  { id: 'lucky', name: 'LUCKY SWIPE', desc: (l) => `SURE CRIT FOR ${pct(0.7 + 0.2 * l)}, USES LUCK`, icon: I.lucky, cost: 1, cooldown: 1, target: 'one', max: 3, effect: (l) => ({ dmg: 0.7 + 0.2 * l, crit: true, scale: 'lck' }) },
  { id: 'flurry', name: 'FLURRY', desc: (l) => `${2 + l} RANDOM HITS FOR 45%, USES AGI`, icon: I.flurry, cost: 2, cooldown: 0, target: 'random', max: 3, effect: (l) => ({ dmg: 0.45, hits: 2 + l, scale: 'agi' }) },
  { id: 'spikes', name: 'TRASH ARMOR', desc: (l) => `5 BLOCK, ATTACKERS TAKE ${3 + 2 * l}`, icon: I.spikes, cost: 1, cooldown: 1, target: 'self', max: 3, effect: (l) => ({ block: 5, self: { thorns: 3 + 2 * l } }) },
  { id: 'bash', name: 'LID BASH', desc: (l) => `HIT FOR 60% AND GAIN ${3 + 2 * l} BLOCK`, icon: I.bash, cost: 1, cooldown: 0, target: 'one', max: 3, effect: (l) => ({ dmg: 0.6, block: 3 + 2 * l }) },
  { id: 'storm', name: 'TRASH STORM', desc: (l) => `${4 + 2 * l} RANDOM HITS FOR 60%`, icon: I.storm, cost: 3, cooldown: 1, target: 'random', max: 3, effect: (l) => ({ dmg: 0.6, hits: 4 + 2 * l }) },
  { id: 'berserk', name: 'BERSERK', desc: (l) => `+50% DAMAGE FOR ${1 + l} TURNS`, icon: I.berserk, cost: 1, cooldown: 3, target: 'self', max: 3, effect: (l) => ({ self: { rage: 1 + l } }) },
  { id: 'dumpster', name: 'DUMPSTER', desc: (l) => `HEAL ${10 + 5 * l}% AND GAIN ${4 + 2 * l} BLOCK`, icon: I.dumpster, cost: 2, cooldown: 2, target: 'self', max: 3, effect: (l) => ({ heal: 0.1 + 0.05 * l, block: 4 + 2 * l }) },
  { id: 'sludge', name: 'SLUDGE BALL', desc: (l) => `HIT 50%, POISON ${2 + l} AND WEAKEN`, icon: I.sludge, cost: 1, cooldown: 1, target: 'one', max: 3, effect: (l) => ({ dmg: 0.5, apply: { poison: 2 + l, weak: 1 } }) },

  // ---- new
  { id: 'quickjab', name: 'QUICK JAB', desc: (l) => `FREE HIT FOR ${pct(0.45 + 0.1 * l)}, USES AGI`, icon: I.quickjab, cost: 0, cooldown: 1, target: 'one', max: 3, effect: (l) => ({ dmg: 0.45 + 0.1 * l, scale: 'agi' }) },
  { id: 'doubletap', name: 'DOUBLE TAP', desc: (l) => `HIT A FOE TWICE FOR ${pct(0.45 + 0.1 * l)}`, icon: I.doubletap, cost: 1, cooldown: 1, target: 'one', max: 3, effect: (l) => ({ dmg: 0.45 + 0.1 * l, hits: 2 }) },
  { id: 'headbutt', name: 'HEADBUTT', desc: (l) => `HIT ${pct(0.8 + 0.2 * l)} AND STUN, LOSE 3 HP`, icon: I.headbutt, cost: 2, cooldown: 3, target: 'one', max: 3, effect: (l) => ({ dmg: 0.8 + 0.2 * l, apply: { stun: 1 }, hpCost: 3 }) },
  { id: 'bodyslam', name: 'BODY SLAM', desc: (l) => `HIT FOR ${pct(1 + 0.3 * l)}, USES DEFENSE`, icon: I.bodyslam, cost: 2, cooldown: 1, target: 'one', max: 3, effect: (l) => ({ dmg: 1 + 0.3 * l, scale: 'def' }) },
  { id: 'snipe', name: 'SNIPE', desc: (l) => `SURE CRIT FOR ${pct(1.2 + 0.3 * l)}, USES LUCK`, icon: I.snipe, cost: 2, cooldown: 2, target: 'one', max: 3, effect: (l) => ({ dmg: 1.2 + 0.3 * l, crit: true, scale: 'lck' }) },
  { id: 'reckless', name: 'RECKLESS', desc: (l) => `HIT FOR ${pct(1.5 + 0.3 * l)}, LOSE 5 HP`, icon: I.reckless, cost: 1, cooldown: 1, target: 'one', max: 3, effect: (l) => ({ dmg: 1.5 + 0.3 * l, hpCost: 5 }) },
  { id: 'toxicbite', name: 'TOXIC BITE', desc: (l) => `BITE FOR 50% AND POISON ${2 + l}`, icon: I.toxicbite, cost: 1, cooldown: 0, target: 'one', max: 3, effect: (l) => ({ dmg: 0.5, apply: { poison: 2 + l } }) },
  { id: 'cantoss', name: 'CAN TOSS', desc: (l) => `${1 + l} RANDOM HITS 50%, EACH WEAKENS`, icon: I.cantoss, cost: 1, cooldown: 1, target: 'random', max: 3, effect: (l) => ({ dmg: 0.5, hits: 1 + l, apply: { weak: 1 } }) },
  { id: 'whirlwind', name: 'WHIRLWIND', desc: (l) => `HIT ALL TWICE FOR ${pct(0.35 + 0.1 * l)}, USES AGI`, icon: I.whirlwind, cost: 2, cooldown: 2, target: 'all', max: 3, effect: (l) => ({ dmg: 0.35 + 0.1 * l, hits: 2, scale: 'agi' }) },
  { id: 'curlup', name: 'CURL UP', desc: (l) => `GAIN ${8 + 4 * l} BLOCK, BUT WEAK 1 TURN`, icon: I.curlup, cost: 1, cooldown: 2, target: 'self', max: 3, effect: (l) => ({ block: 8 + 4 * l, self: { weak: 1 } }) },
  { id: 'playdead', name: 'PLAY DEAD', desc: (l) => `GAIN ${14 + 6 * l} BLOCK AND HEAL 5%`, icon: I.playdead, cost: 2, cooldown: 4, target: 'self', max: 3, effect: (l) => ({ block: 14 + 6 * l, heal: 0.05 }) },
  { id: 'lickwounds', name: 'LICK WOUNDS', desc: (l) => `FREE: HEAL ${6 + 3 * l}% HEALTH`, icon: I.lickwounds, cost: 0, cooldown: 3, target: 'self', max: 3, effect: (l) => ({ heal: 0.06 + 0.03 * l }) },
  { id: 'sugarrush', name: 'SUGAR RUSH', desc: (l) => `+${1 + l} AP, TAKE +50% FOR 1 TURN`, icon: I.sugarrush, cost: 0, cooldown: 3, target: 'self', max: 2, effect: (l) => ({ ap: 1 + l, self: { vuln: 1 } }) },
  { id: 'burp', name: 'BIG BURP', desc: (l) => `HIT ALL 30%, THEY TAKE +50% ${1 + l} TURNS`, icon: I.burp, cost: 1, cooldown: 2, target: 'all', max: 3, effect: (l) => ({ dmg: 0.3, apply: { vuln: 1 + l } }) },
  { id: 'howl', name: 'HOWL', desc: (l) => `YOU +50% DMG, FOES WEAK, ${l} TURN${l > 1 ? 'S' : ''}`, icon: I.howl, cost: 1, cooldown: 3, target: 'all', max: 3, effect: (l) => ({ apply: { weak: l }, self: { rage: l } }) },
  { id: 'shrapnel', name: 'SHRAPNEL', desc: (l) => `HIT ALL FOR 35%, POISON ALL ${1 + l}`, icon: I.shrapnel, cost: 2, cooldown: 1, target: 'all', max: 3, effect: (l) => ({ dmg: 0.35, apply: { poison: 1 + l } }) },
  { id: 'comet', name: 'COMET DROP', desc: (l) => `MASSIVE HIT FOR ${pct(3 + 0.5 * l)}`, icon: I.comet, cost: 3, cooldown: 4, target: 'one', max: 3, effect: (l) => ({ dmg: 3 + 0.5 * l }) },
  { id: 'thunder', name: 'THUNDERCLAP', desc: (l) => `HIT ALL FOR ${pct(0.7 + 0.2 * l)} AND WEAKEN`, icon: I.thunder, cost: 3, cooldown: 3, target: 'all', max: 3, effect: (l) => ({ dmg: 0.7 + 0.2 * l, apply: { weak: 1 } }) },
];
