// Bosses. One waits at the end of each area; at half health (phase2.at) each one swaps to
// a nastier move set and, where given, angrier frames. Art lives in boss_art.ts.
import type { EnemyDef } from '../types';
import { frames2, recolor } from './art';
import * as A from './boss_art';

const VAN = frames2(A.VAN_A, A.VAN_B);
const GOOSE = frames2(A.GOOSE_A, A.GOOSE_B);
const RAT_KING = frames2(A.RAT_KING_A, A.RAT_KING_B);
const BEAR = frames2(A.BEAR_A, A.BEAR_B);
const OLD_GATOR = frames2(A.OLD_GATOR_A, A.OLD_GATOR_B);
const MUSHROOM_QUEEN = frames2(A.MUSHROOM_QUEEN_A, A.MUSHROOM_QUEEN_B);
const CRYSTAL_GOLEM = frames2(A.CRYSTAL_GOLEM_A, A.CRYSTAL_GOLEM_B);
const SWAMP_WITCH = frames2(A.SWAMP_WITCH_A, A.SWAMP_WITCH_B);
const CLOCKWORK_MECH = frames2(A.CLOCKWORK_MECH_A, A.CLOCKWORK_MECH_B);
const SKY_KRAKEN = frames2(A.SKY_KRAKEN_A, A.SKY_KRAKEN_B);
const UFO = frames2(A.UFO_A, A.UFO_B);
const TRASH_GOD = frames2(A.TRASH_GOD_A, A.TRASH_GOD_B);

export const BOSSES: EnemyDef[] = [
  // ---------------------------------------------------------------- tier 1
  {
    id: 'van',
    name: 'ANIMAL CONTROL VAN',
    boss: true,
    frames: VAN,
    fps: 4,
    hp: 95,
    opener: 'net',
    moves: [
      { id: 'net', name: 'NET LAUNCHER', intent: 'debuff', dmg: 4, apDrain: 1, weight: 2 },
      { id: 'ram', name: 'RAM', intent: 'attack', dmg: 11, weight: 2 },
      { id: 'horn', name: 'HORN BLAST', intent: 'debuff', apply: { weak: 2 }, weight: 1 },
      { id: 'backup', name: 'CALL BACKUP', intent: 'summon', summon: 'rat', weight: 1 },
      { id: 'rev', name: 'REV ENGINE', intent: 'charge', weight: 1, after: 'fullram' },
      { id: 'fullram', name: 'FULL SPEED RAM', intent: 'attack', dmg: 24, weight: 0 },
    ],
    phase2: {
      at: 0.5,
      name: 'VAN IN OVERDRIVE',
      frames: recolor(VAN, { c: 'R', C: 'q', b: 'r' }),
      moves: [
        { id: 'siren', name: 'SIREN WAIL', intent: 'debuff', apply: { weak: 2, vuln: 2 }, weight: 1 },
        { id: 'screech', name: 'TIRE SCREECH', intent: 'multi', dmg: 5, hits: 3, weight: 2 },
        { id: 'ram', name: 'RAM', intent: 'attack', dmg: 14, weight: 2 },
        { id: 'k9', name: 'RELEASE THE DOG', intent: 'summon', summon: 'dog', weight: 1, once: true },
        { id: 'rev', name: 'REDLINE', intent: 'charge', weight: 1, after: 'fullram' },
        { id: 'fullram', name: 'FULL SPEED RAM', intent: 'attack', dmg: 30, weight: 0 },
      ],
    },
    xp: 40,
    shinies: 30,
    colors: [0xf4f4f4, 0xb13e53, 0x3b5dc9],
  },
  {
    id: 'goose',
    name: 'THE GOOSE',
    boss: true,
    frames: GOOSE,
    fps: 3,
    hp: 90,
    dodge: 0.1,
    opener: 'honk',
    moves: [
      { id: 'honk', name: 'HONK!', intent: 'debuff', apply: { weak: 2, vuln: 2 }, weight: 1 },
      { id: 'peck', name: 'PECK FLURRY', intent: 'multi', dmg: 4, hits: 3, weight: 2 },
      { id: 'yoink', name: 'YOINK', intent: 'steal', dmg: 3, steal: 8, weight: 1 },
      { id: 'flap', name: 'FLAP', intent: 'block', block: 16, weight: 1 },
      { id: 'windup', name: 'STRETCH NECK', intent: 'charge', weight: 1, after: 'rampage' },
      { id: 'rampage', name: 'GOOSE RAMPAGE', intent: 'attack', dmg: 26, weight: 0 },
    ],
    phase2: {
      at: 0.5,
      name: 'GOOSE OF WAR',
      frames: recolor(GOOSE, { H: 'r', O: 'q', y: 'o' }),
      moves: [
        { id: 'honk', name: 'HONK HONK!', intent: 'debuff', apply: { weak: 3, vuln: 2 }, apDrain: 1, weight: 1 },
        { id: 'peck', name: 'PECK FRENZY', intent: 'multi', dmg: 5, hits: 3, weight: 2 },
        { id: 'yoink', name: 'MEGA YOINK', intent: 'steal', dmg: 4, steal: 12, weight: 1 },
        { id: 'flock', name: 'RALLY THE FLOCK', intent: 'summon', summon: 'pigeon', weight: 1 },
        { id: 'windup', name: 'STRETCH NECK', intent: 'charge', weight: 1, after: 'rampage' },
        { id: 'rampage', name: 'GOOSE RAMPAGE', intent: 'attack', dmg: 32, weight: 0 },
      ],
    },
    xp: 40,
    shinies: 30,
    colors: [0xf4f4f4, 0xffa300, 0x94b0c2],
  },
  {
    id: 'rat_king',
    name: 'THE RAT KING',
    boss: true,
    frames: RAT_KING,
    fps: 3,
    hp: 110,
    opener: 'summon',
    moves: [
      { id: 'summon', name: 'SUMMON SUBJECTS', intent: 'summon', summon: 'rat', weight: 2 },
      { id: 'plague', name: 'PLAGUE', intent: 'debuff', apply: { poison: 6 }, weight: 1 },
      { id: 'slam', name: 'SCEPTER SLAM', intent: 'attack', dmg: 14, weight: 2 },
      { id: 'decree', name: 'ROYAL DECREE', intent: 'debuff', apply: { weak: 2 }, apDrain: 1, weight: 1 },
      { id: 'feast', name: 'ROYAL FEAST', intent: 'heal', heal: 0.15, weight: 1 },
    ],
    phase2: {
      at: 0.5,
      name: 'MAD RAT KING',
      heal: 0.1,
      frames: recolor(RAT_KING, { H: 'q', Y: 'q', y: 'r' }),
      moves: [
        { id: 'summon', name: 'SUMMON SUBJECTS', intent: 'summon', summon: 'rat', weight: 2 },
        { id: 'plague', name: 'BLACK PLAGUE', intent: 'debuff', apply: { poison: 8, weak: 1 }, weight: 1 },
        { id: 'rally', name: 'LONG LIVE THE KING', intent: 'buff', buff: { rage: 3 }, allies: true, weight: 1 },
        { id: 'slam', name: 'SCEPTER SLAM', intent: 'attack', dmg: 17, weight: 2 },
        { id: 'throne', name: 'RAISE SCEPTER', intent: 'charge', weight: 1, after: 'smite' },
        { id: 'smite', name: 'ROYAL SMITE', intent: 'attack', dmg: 30, weight: 0 },
      ],
    },
    xp: 60,
    shinies: 45,
    colors: [0x94b0c2, 0xffcd75, 0xb13e53],
  },
  // ---------------------------------------------------------------- tier 2-3
  {
    id: 'bear',
    name: 'BIG BEAR',
    boss: true,
    frames: BEAR,
    fps: 2,
    hp: 125,
    opener: 'roar',
    moves: [
      { id: 'roar', name: 'ROAR', intent: 'debuff', apply: { weak: 2, vuln: 1 }, weight: 1 },
      { id: 'maul', name: 'MAUL', intent: 'attack', dmg: 14, weight: 2 },
      { id: 'swipe', name: 'DOUBLE SWIPE', intent: 'multi', dmg: 6, hits: 2, weight: 2 },
      { id: 'honey', name: 'HONEY BREAK', intent: 'heal', heal: 0.12, weight: 1 },
      { id: 'rear', name: 'REAR UP', intent: 'charge', weight: 1, after: 'hug' },
      { id: 'hug', name: 'BEAR HUG', intent: 'attack', dmg: 30, apply: { stun: 1 }, weight: 0 },
    ],
    phase2: {
      at: 0.5,
      name: 'GRIZZLY RAGE',
      frames: recolor(BEAR, { H: 'r', R: 'q' }),
      moves: [
        { id: 'roar', name: 'BELLOW', intent: 'buff', buff: { rage: 3 }, weight: 1 },
        { id: 'maul', name: 'MAUL', intent: 'attack', dmg: 17, weight: 2 },
        { id: 'frenzy', name: 'CLAW FRENZY', intent: 'multi', dmg: 6, hits: 3, weight: 2 },
        { id: 'fur', name: 'THICK FUR', intent: 'block', block: 20, weight: 1 },
        { id: 'rear', name: 'REAR UP', intent: 'charge', weight: 1, after: 'crush' },
        { id: 'crush', name: 'BEAR CRUSH', intent: 'attack', dmg: 36, apply: { stun: 1 }, weight: 0 },
      ],
    },
    xp: 70,
    shinies: 50,
    colors: [0x8f563b, 0xd6a77a, 0x5c3a2e],
  },
  {
    id: 'old_gator',
    name: 'OLD GATOR',
    boss: true,
    frames: OLD_GATOR,
    fps: 2,
    hp: 135,
    armor: 2,
    opener: 'lurk',
    moves: [
      { id: 'lurk', name: 'LURK', intent: 'block', block: 18, weight: 1 },
      { id: 'chomp', name: 'CHOMP', intent: 'attack', dmg: 15, weight: 2 },
      { id: 'tail', name: 'TAIL SWEEP', intent: 'multi', dmg: 7, hits: 2, weight: 2 },
      { id: 'leeches', name: 'SWAMP FRIENDS', intent: 'summon', summon: 'leech', weight: 1 },
      { id: 'submerge', name: 'SUBMERGE', intent: 'block', block: 18, weight: 1, after: 'roll' },
      { id: 'roll', name: 'DEATH ROLL', intent: 'attack', dmg: 30, weight: 0 },
    ],
    phase2: {
      at: 0.5,
      name: 'ANCIENT JAWS',
      heal: 0.1,
      frames: recolor(OLD_GATOR, { y: 'q', R: 'q' }),
      moves: [
        { id: 'chomp', name: 'CHOMP', intent: 'attack', dmg: 18, weight: 2 },
        { id: 'tail', name: 'TAIL STORM', intent: 'multi', dmg: 7, hits: 3, weight: 2 },
        { id: 'frogs', name: 'BELLOW', intent: 'summon', summon: 'frog', weight: 1 },
        { id: 'swallow', name: 'SWALLOW SHINIES', intent: 'steal', dmg: 6, steal: 15, weight: 1 },
        { id: 'gape', name: 'GAPING MAW', intent: 'charge', weight: 1, after: 'megachomp' },
        { id: 'megachomp', name: 'MEGA CHOMP', intent: 'attack', dmg: 38, weight: 0 },
      ],
    },
    xp: 75,
    shinies: 55,
    colors: [0x6a8f3a, 0x2d6a3e, 0xfff6e0],
  },
  // ---------------------------------------------------------------- tier 3-4
  {
    id: 'swamp_witch',
    name: 'SWAMP WITCH',
    boss: true,
    frames: SWAMP_WITCH,
    fps: 3,
    hp: 130,
    opener: 'hex',
    moves: [
      { id: 'hex', name: 'HEX', intent: 'debuff', apply: { weak: 2, vuln: 2 }, weight: 1 },
      { id: 'brew', name: 'BUBBLING BREW', intent: 'debuff', apply: { poison: 6 }, weight: 2 },
      { id: 'zap', name: 'WART ZAP', intent: 'attack', dmg: 12, weight: 2 },
      { id: 'toad', name: 'TOAD CURSE', intent: 'summon', summon: 'frog', weight: 1 },
      { id: 'stir', name: 'STIR CAULDRON', intent: 'charge', weight: 1, after: 'boil' },
      { id: 'boil', name: 'BOIL OVER', intent: 'attack', dmg: 28, apply: { poison: 3 }, weight: 0 },
    ],
    phase2: {
      at: 0.5,
      name: 'HAG OF THE BOG',
      heal: 0.1,
      frames: recolor(SWAMP_WITCH, { C: 'q', t: 'o', D: 'R', Y: 'r' }),
      moves: [
        { id: 'hex', name: 'DOUBLE HEX', intent: 'debuff', apply: { weak: 3, vuln: 3 }, apDrain: 1, weight: 1 },
        { id: 'brew', name: 'BLOOD BREW', intent: 'debuff', apply: { poison: 10 }, weight: 2 },
        { id: 'zap', name: 'WART BARRAGE', intent: 'multi', dmg: 6, hits: 3, weight: 2 },
        { id: 'leech', name: 'LEECH CURSE', intent: 'summon', summon: 'leech', weight: 1 },
        { id: 'stir', name: 'STIR CAULDRON', intent: 'charge', weight: 1, after: 'boil' },
        { id: 'boil', name: 'BOIL OVER', intent: 'attack', dmg: 34, apply: { poison: 4 }, weight: 0 },
      ],
    },
    xp: 80,
    shinies: 60,
    colors: [0xa7f070, 0x73eff7, 0x2d6a3e],
  },
  {
    id: 'mushroom_queen',
    name: 'MUSHROOM QUEEN',
    boss: true,
    frames: MUSHROOM_QUEEN,
    fps: 2,
    hp: 130,
    regen: 3,
    opener: 'court',
    moves: [
      { id: 'court', name: 'SUMMON COURT', intent: 'summon', summon: 'shroomling', weight: 1 },
      { id: 'storm', name: 'SPORE STORM', intent: 'debuff', apply: { poison: 5, weak: 1 }, weight: 2 },
      { id: 'bless', name: 'ROYAL BLESSING', intent: 'heal', heal: 0.15, allies: true, weight: 1 },
      { id: 'bonk', name: 'SCEPTER BONK', intent: 'attack', dmg: 13, weight: 2 },
      { id: 'bloom', name: 'BLOOM', intent: 'charge', weight: 1, after: 'nova' },
      { id: 'nova', name: 'SPORE NOVA', intent: 'attack', dmg: 28, weight: 0 },
    ],
    phase2: {
      at: 0.5,
      name: 'BLIGHT QUEEN',
      heal: 0.12,
      frames: recolor(MUSHROOM_QUEEN, { v: 'z', e: 'F', u: 'E', Q: 'm', w: 'L' }),
      moves: [
        { id: 'puffers', name: 'SUMMON PUFFER', intent: 'summon', summon: 'spore_puffer', weight: 1 },
        { id: 'storm', name: 'BLIGHT STORM', intent: 'debuff', apply: { poison: 8, weak: 2 }, weight: 2 },
        { id: 'rot', name: 'ROT TOUCH', intent: 'attack', dmg: 15, apply: { vuln: 2 }, weight: 2 },
        { id: 'decree', name: 'SPORE DECREE', intent: 'buff', buff: { rage: 3 }, allies: true, weight: 1 },
        { id: 'bloom', name: 'DARK BLOOM', intent: 'charge', weight: 1, after: 'nova' },
        { id: 'nova', name: 'BLIGHT NOVA', intent: 'attack', dmg: 34, weight: 0 },
      ],
    },
    xp: 80,
    shinies: 60,
    colors: [0xb05ccf, 0xfff6e0, 0x9be2b0],
  },
  {
    id: 'crystal_golem',
    name: 'CRYSTAL GOLEM',
    boss: true,
    frames: CRYSTAL_GOLEM,
    fps: 2,
    hp: 145,
    armor: 4,
    opener: 'harden',
    moves: [
      { id: 'harden', name: 'HARDEN', intent: 'block', block: 20, weight: 1 },
      { id: 'punch', name: 'CRYSTAL PUNCH', intent: 'attack', dmg: 15, weight: 2 },
      { id: 'shards', name: 'SHARD SPRAY', intent: 'multi', dmg: 5, hits: 3, weight: 2 },
      { id: 'reflect', name: 'MIRROR SKIN', intent: 'buff', buff: { thorns: 4 }, weight: 1 },
      { id: 'core', name: 'CHARGE CORE', intent: 'charge', weight: 1, after: 'beam' },
      { id: 'beam', name: 'PRISM BEAM', intent: 'attack', dmg: 32, weight: 0 },
    ],
    phase2: {
      at: 0.5,
      name: 'SHATTERED GOLEM',
      frames: recolor(CRYSTAL_GOLEM, { C: 'h', i: 'P', c: 'M', b: 'e', t: 'h', D: 'M' }),
      moves: [
        { id: 'shards', name: 'SHARD STORM', intent: 'multi', dmg: 6, hits: 4, weight: 2 },
        { id: 'punch', name: 'CRYSTAL PUNCH', intent: 'attack', dmg: 18, weight: 2 },
        { id: 'resonate', name: 'RESONATE', intent: 'debuff', apply: { vuln: 3, weak: 1 }, weight: 1 },
        { id: 'mend', name: 'REGROW', intent: 'heal', heal: 0.1, weight: 1 },
        { id: 'core', name: 'OVERLOAD CORE', intent: 'charge', weight: 1, after: 'beam' },
        { id: 'beam', name: 'PRISM CANNON', intent: 'attack', dmg: 40, weight: 0 },
      ],
    },
    xp: 85,
    shinies: 65,
    colors: [0x73eff7, 0x94b0c2, 0xc7f2ff],
  },
  {
    id: 'clockwork_mech',
    name: 'CLOCKWORK MECH',
    boss: true,
    frames: CLOCKWORK_MECH,
    fps: 2,
    hp: 150,
    armor: 3,
    opener: 'windup',
    moves: [
      { id: 'windup', name: 'WIND UP', intent: 'buff', buff: { rage: 2 }, weight: 1 },
      { id: 'cannon', name: 'CANNON SHOT', intent: 'attack', dmg: 16, weight: 2 },
      { id: 'grind', name: 'GEAR GRIND', intent: 'multi', dmg: 5, hits: 3, weight: 2 },
      { id: 'drone', name: 'DEPLOY DRONE', intent: 'summon', summon: 'drone', weight: 1 },
      { id: 'tick', name: 'TICK TOCK', intent: 'charge', weight: 1, after: 'alarm' },
      { id: 'alarm', name: 'ALARM BLAST', intent: 'attack', dmg: 32, apply: { stun: 1 }, weight: 0 },
    ],
    phase2: {
      at: 0.5,
      name: 'OVERWOUND MECH',
      frames: recolor(CLOCKWORK_MECH, { y: 'o', O: 'q', S: 'R', U: 'R', Q: 'Y', T: 's' }),
      moves: [
        { id: 'cannon', name: 'CANNON SHOT', intent: 'attack', dmg: 20, weight: 2 },
        { id: 'missiles', name: 'MISSILE BARRAGE', intent: 'multi', dmg: 6, hits: 4, weight: 2 },
        { id: 'vent', name: 'STEAM VENT', intent: 'block', block: 22, weight: 1 },
        { id: 'drone', name: 'DEPLOY DRONE', intent: 'summon', summon: 'drone', weight: 1 },
        { id: 'tick', name: 'TICK TOCK TICK', intent: 'charge', weight: 1, after: 'midnight' },
        { id: 'midnight', name: 'MIDNIGHT STRIKE', intent: 'attack', dmg: 40, apply: { stun: 1 }, weight: 0 },
      ],
    },
    xp: 90,
    shinies: 70,
    colors: [0xffa300, 0xffcd75, 0x94b0c2],
  },
  // ---------------------------------------------------------------- tier 5
  {
    id: 'sky_kraken',
    name: 'SKY KRAKEN',
    boss: true,
    flyer: true,
    frames: SKY_KRAKEN,
    fps: 3,
    hp: 165,
    dodge: 0.1,
    opener: 'ink',
    moves: [
      { id: 'ink', name: 'INK CLOUD', intent: 'debuff', apply: { weak: 2, vuln: 1 }, apDrain: 1, weight: 1 },
      { id: 'slap', name: 'TENTACLE SLAP', intent: 'multi', dmg: 6, hits: 3, weight: 2 },
      { id: 'grab', name: 'PICKPOCKET ARMS', intent: 'steal', dmg: 6, steal: 15, weight: 1 },
      { id: 'jelly', name: 'CALL THE JELLIES', intent: 'summon', summon: 'star_jelly', weight: 1 },
      { id: 'coil', name: 'COIL UP', intent: 'charge', weight: 1, after: 'grip' },
      { id: 'grip', name: 'CRUSHING GRIP', intent: 'attack', dmg: 34, weight: 0 },
    ],
    phase2: {
      at: 0.5,
      name: 'STORM KRAKEN',
      heal: 0.1,
      frames: recolor(SKY_KRAKEN, { v: 'b', e: 'B', u: 'I', h: 'C', M: 'c', P: 'C', y: 'Y', O: 'y' }),
      moves: [
        { id: 'slap', name: 'TENTACLE STORM', intent: 'multi', dmg: 7, hits: 4, weight: 2 },
        { id: 'thunder', name: 'THUNDER INK', intent: 'attack', dmg: 18, apply: { stun: 1 }, weight: 2 },
        { id: 'grab', name: 'GRABBY ARMS', intent: 'steal', dmg: 8, steal: 20, weight: 1 },
        { id: 'jelly', name: 'CALL THE JELLIES', intent: 'summon', summon: 'star_jelly', weight: 1 },
        { id: 'coil', name: 'GATHER STORM', intent: 'charge', weight: 1, after: 'maelstrom' },
        { id: 'maelstrom', name: 'MAELSTROM', intent: 'attack', dmg: 42, weight: 0 },
      ],
    },
    xp: 100,
    shinies: 80,
    colors: [0xb05ccf, 0xff77c8, 0x3b1f5c],
  },
  {
    id: 'ufo',
    name: 'UFO',
    boss: true,
    flyer: true,
    frames: UFO,
    fps: 4,
    hp: 160,
    dodge: 0.15,
    opener: 'scan',
    moves: [
      { id: 'scan', name: 'DEEP SCAN', intent: 'debuff', apply: { vuln: 3 }, weight: 1 },
      { id: 'laser', name: 'LASER', intent: 'attack', dmg: 16, weight: 2 },
      { id: 'abduct', name: 'ABDUCT SHINIES', intent: 'steal', dmg: 6, steal: 20, weight: 1 },
      { id: 'grub', name: 'DROP GRUB', intent: 'summon', summon: 'alien_grub', weight: 1 },
      { id: 'beam', name: 'CHARGE BEAM', intent: 'charge', weight: 1, after: 'ray' },
      { id: 'ray', name: 'DEATH RAY', intent: 'attack', dmg: 38, weight: 0 },
    ],
    phase2: {
      at: 0.5,
      name: 'MOTHERSHIP MODE',
      frames: recolor(UFO, { y: 'q', G: 'q', i: 'P', C: 'h', c: 'M', L: 'o', F: 'R' }),
      moves: [
        { id: 'laser', name: 'LASER GRID', intent: 'multi', dmg: 8, hits: 3, weight: 2 },
        { id: 'probe', name: 'MIND PROBE', intent: 'debuff', apply: { weak: 2, vuln: 2 }, apDrain: 2, weight: 1 },
        { id: 'imp', name: 'LAUNCH COMET', intent: 'summon', summon: 'comet_imp', weight: 1 },
        { id: 'field', name: 'FORCE FIELD', intent: 'block', block: 28, weight: 1 },
        { id: 'beam', name: 'CHARGE BEAM', intent: 'charge', weight: 1, after: 'ray' },
        { id: 'ray', name: 'ANNIHILATION RAY', intent: 'attack', dmg: 46, weight: 0 },
      ],
    },
    xp: 100,
    shinies: 80,
    colors: [0x94b0c2, 0x73eff7, 0xa7f070],
  },
  {
    id: 'trash_god',
    name: 'TRASH GOD',
    boss: true,
    frames: TRASH_GOD,
    fps: 2,
    hp: 185,
    armor: 3,
    regen: 4,
    opener: 'stench',
    moves: [
      { id: 'stench', name: 'DIVINE STENCH', intent: 'debuff', apply: { poison: 6, weak: 1 }, weight: 1 },
      { id: 'slam', name: 'GARBAGE SLAM', intent: 'attack', dmg: 18, weight: 2 },
      { id: 'storm', name: 'TRASH STORM', intent: 'multi', dmg: 6, hits: 4, weight: 2 },
      { id: 'vermin', name: 'SUMMON VERMIN', intent: 'summon', summon: 'crow', weight: 1 },
      { id: 'compact', name: 'COMPACT', intent: 'charge', weight: 1, after: 'crush' },
      { id: 'crush', name: 'TRASH COMPACTOR', intent: 'attack', dmg: 40, weight: 0 },
    ],
    phase2: {
      at: 0.5,
      name: 'TRASH GOD ASCENDED',
      heal: 0.15,
      frames: recolor(TRASH_GOD, { L: 'q', Y: 'y', F: 'R', G: 'r', E: 'u' }),
      moves: [
        { id: 'stench', name: 'HOLY STENCH', intent: 'debuff', apply: { poison: 10, weak: 2, vuln: 2 }, weight: 1 },
        { id: 'storm', name: 'TRASH TYPHOON', intent: 'multi', dmg: 7, hits: 4, weight: 3 },
        { id: 'devour', name: 'DEVOUR SHINIES', intent: 'steal', dmg: 8, steal: 25, weight: 1 },
        { id: 'mold', name: 'SPAWN MOLD', intent: 'summon', summon: 'mold_blob', weight: 1 },
        { id: 'compact', name: 'COMPACT', intent: 'charge', weight: 1, after: 'landfill' },
        { id: 'landfill', name: 'LANDFILL', intent: 'attack', dmg: 50, weight: 0 },
      ],
    },
    xp: 120,
    shinies: 100,
    colors: [0x38b764, 0xa7f070, 0x86745a],
  },
];
