// Fungi family: the damp forest floor gets up and walks. Stage 15 on.
import type { EnemyDef } from '../types';
import { frames } from './art';

const SHROOMLING = [
  '.....rrrrr......',
  '...rrPwwrrrr....',
  '..rPPwwwrrwwr...',
  '.rPPrrwrrrwwwr..',
  '.rPrrrrrrrrwrrr.',
  'rrwwrrrrwwrrrrRR',
  'rwwwrrrrwwrrrRRR',
  'RRwRRRRRRRRRRRRR',
  '.RRRRRRRRRRRRRR.',
  '...QQQQQQQQQQ...',
  '...QkQkQQQQQT...',
  '...QkQkQQQQQT...',
  '..PQQQQQQQQTT...',
  '...QkkQQQQQTT...',
  '...QQQQQQQTTT...',
  '...TTTTTTTTTT...',
  '...jj....jj.....',
];

const PUFFER = [
  '.......m...........',
  '......mLm..m.......',
  '.......m..mLm......',
  '.......QQQQ.m......',
  '.....QQQQQQss......',
  '....QQsQQQsssS.....',
  '...QQQQQQsssssS....',
  '..QQkQQkQssssSSS...',
  '..QQkQQkssssssSSS..',
  '.QQQQQQssssssSSSS..',
  '.QsQkkkssssssSSSS..',
  '.QQssssssssssSSSS..',
  '..ssssssssSSSSSSS..',
  '...SSSSSSSSSSSSS...',
  '....SSSSSSSSSS.....',
  '.....jjj..jjj......',
];

const KNIGHT = [
  '.......vvvvvv............',
  '.....vvhhvvvvvv..........',
  '...vvhhwwvvvvwwvv.....l..',
  '..vhhwwwvvvvwwwwvv...lwl.',
  '..vhvvwvvvvvvwwvvve..lwl.',
  '.vvvvvvvvvwwvvvvvvee..J..',
  '.vwwvvvvvwwwwvvvveee..J..',
  'eeeeeeeeeeeeeeeeeeeee.J..',
  '...QQQQQQQQQQQQQQ.....J..',
  '...QkkQQkkQQQQQTT.....J..',
  '...QQQQQQQQQQQQTT.....J..',
  '..lllllllllllllllgg..gJ..',
  'yyyyylllllllllllllggggJ..',
  'yOOOOylllllllllllllggggg.',
  'yOrrOyllllllgllllllgggJ..',
  'yOrrOylllllllglllllggdJ..',
  'yOQQOylllllllglllllgddJ..',
  'yOQQOygggggggggggggdddJ..',
  'yOOOOyddddddddddddddd.J..',
  '.yOOyllllgg....llggd..J..',
  '..yy.llllgg....llggd..J..',
  '.....ggggdd....ggddd..J..',
  '....dddddd....ddddd...J..',
];

const MOLD = [
  '..........zzzzzz..........',
  '.......zzmmmzzzzzz........',
  '.....zzmmmzzzzzzLzzz......',
  '....zmmmzzzzzLLzzzzzz.....',
  '...zmwwzzzwwzzzzzzzzzz....',
  '..zmwkwzzwkwzzzzzzzzzzF...',
  '..zzwwzzzzwwzzzLzzzzzzFF..',
  '.zzzzzzzzzzzzzLLLzzzzzzFF.',
  '.zzLzkkkkkkzzzzLzzzzLzzFF.',
  'zzLLLkRRRRkzzzzzzzzLLLzFFF',
  'zzzLzzkkkkzzzzzzzzzzLzzFFF',
  'zzzzzzzzzzzzzzzzzzzzzzFFFF',
  '.FzzzzzzzzzzzzzzzzzzzFFFF.',
  'FFFFzzzzzzzzzzzzzzzFFFFFFF',
  'FFFFFFFFFFFFFFFFFFFFFFFFFF',
];

const MOLD_BIT = [
  '....zzzz...',
  '..zmmzzzz..',
  '.zmzzzzzzz.',
  '.zwkzwkzzzF',
  'zzzzzzzzzFF',
  'zzzkkkzzzFF',
  'FFzzzzzzFFF',
  'FFFFFFFFFFF',
];

const HOG = [
  '.........NN.N.N.N..............',
  '.......NNnNnNnNnNN.............',
  '......nTTTTTTnnnnnNN...........',
  '....TTTTTTTTTTnnnnnnnnnnn......',
  '...TTkTTTTTTTTTnnnnnnnnnnnn....',
  '..TTTTTTTTTTTTnnnnnnnnnnnnnn...',
  'PPTTTTTTTTTTTnnnnnnnnnnnnnnnn..',
  'PkPTTTTTTTTTnnnnnnnnnnnnnnnnnN.',
  'PPPTnTTTTTTnnnnnnnnnnnnnnnnnnNn',
  '.QQnnnTTTnnnnnnnnnnnnnnnnnnnNN.',
  '..QnnnnnnnnnnnnnnnnnnnnnnnnNN..',
  '....nnnnnnnnnnnnnnnnnnnnnnNN...',
  '.....nnNNNNnnNNNNNNNNNnnNNN....',
  '.....nnN.nnN.......nnN.nnN.....',
  '.....nnN.nnN.......nnN.nnN.....',
  '.....kkk.kkk.......kkk.kkk.....',
];

export const ENEMIES_FUNGI: EnemyDef[] = [
  {
    id: 'shroomling',
    name: 'SHROOMLING',
    family: 'fungi',
    role: 'support',
    minStage: 15,
    frames: frames(SHROOMLING, {
      10: '...QkQkQQQQQT...',
      11: '...QQQQQQQQQT...',
      16: '....jj..jj......',
    }),
    fps: 2,
    hp: 22,
    moves: [
      { id: 'spores', name: 'HEALING SPORES', intent: 'heal', heal: 0.22, allies: true, weight: 3 },
      { id: 'cheer', name: 'TINY CHEER', intent: 'buff', buff: { rage: 2 }, allies: true, weight: 1 },
      { id: 'bonk', name: 'CAP BONK', intent: 'attack', dmg: 6, weight: 2 },
    ],
    xp: 12,
    shinies: 4,
    colors: [0xb13e53, 0xf4f4f4, 0xfff6e0],
  },
  {
    id: 'spore_puffer',
    name: 'SPORE PUFFER',
    family: 'fungi',
    role: 'trickster',
    minStage: 15,
    frames: frames(PUFFER, {
      0: '...........m.......',
      1: '.....m....mLm......',
      2: '....mLm....m.......',
      3: '.....m.QQQQ........',
    }),
    fps: 2,
    hp: 20,
    dodge: 0.1,
    onDeath: 'burst',
    moves: [
      { id: 'puff', name: 'SPORE PUFF', intent: 'debuff', apply: { poison: 4, weak: 1 }, weight: 2 },
      { id: 'cloud', name: 'SPORE CLOUD', intent: 'debuff', apply: { vuln: 2 }, apDrain: 1, weight: 2 },
      { id: 'bump', name: 'BUMP', intent: 'attack', dmg: 5, weight: 1 },
    ],
    xp: 12,
    shinies: 5,
    colors: [0xfff6e0, 0xe8c170, 0x9be2b0],
  },
  {
    id: 'toadstool_knight',
    name: 'TOADSTOOL KNIGHT',
    family: 'fungi',
    role: 'guard',
    minStage: 17,
    armor: 4,
    frames: frames(KNIGHT, {
      9: '...QQQQQQQQQQQQTT.....J..',
      2: '...vvhhwwvvvvwwvv.........',
      3: '..vhhwwwvvvvwwwwvv....l...',
      4: '..vhvvwvvvvvvwwvvve..lwl..',
      5: '.vvvvvvvvvwwvvvvvvee.lwl..',
    }),
    fps: 2,
    hp: 32,
    moves: [
      { id: 'wall', name: 'SHIELD WALL', intent: 'block', block: 14, guard: true, weight: 3 },
      { id: 'lance', name: 'LANCE POKE', intent: 'attack', dmg: 9, weight: 2 },
      { id: 'oath', name: 'SPORE OATH', intent: 'buff', buff: { thorns: 3 }, allies: true, weight: 1 },
    ],
    xp: 15,
    shinies: 5,
    colors: [0xb05ccf, 0xf4f4f4, 0x94b0c2],
  },
  {
    id: 'mold_blob',
    name: 'MOLD BLOB',
    family: 'fungi',
    role: 'brute',
    minStage: 16,
    regen: 3,
    onDeath: 'split',
    split: 'mold_bit',
    frames: frames(MOLD, {
      0: '...........................',
      1: '..........zzzzzz..........',
      2: '......zzmmmzzzzzzLzz......',
      3: '....zzmmzzzzzLLzzzzzzz....',
      12: 'FzzzzzzzzzzzzzzzzzzzzFFFFF',
    }),
    fps: 2,
    hp: 44,
    moves: [
      { id: 'engulf', name: 'ENGULF', intent: 'attack', dmg: 12, weight: 3 },
      { id: 'ooze', name: 'OOZE', intent: 'debuff', dmg: 5, apply: { poison: 3 }, weight: 2 },
      { id: 'swell', name: 'SWELL', intent: 'buff', buff: { rage: 2 }, weight: 1 },
    ],
    xp: 16,
    shinies: 5,
    colors: [0x6a8f3a, 0x9be2b0, 0x2d6a3e],
  },
  {
    id: 'mold_bit',
    name: 'MOLD BIT',
    family: 'fungi',
    minStage: 999,
    frames: frames(MOLD_BIT, {
      0: '...........',
      1: '....zzzz...',
      2: '.zzmmzzzzz.',
    }),
    fps: 3,
    hp: 12,
    moves: [
      { id: 'blorp', name: 'BLORP', intent: 'attack', dmg: 4, weight: 2 },
      { id: 'spit', name: 'SPIT MOLD', intent: 'debuff', apply: { poison: 2 }, weight: 1 },
    ],
    xp: 3,
    shinies: 1,
    colors: [0x6a8f3a, 0x9be2b0, 0x2d6a3e],
  },
  {
    id: 'truffle_hog',
    name: 'TRUFFLE HOG',
    family: 'fungi',
    role: 'charger',
    minStage: 18,
    frames: frames(HOG, {
      0: '.........N.N.N.N...............',
      1: '.......NNnNnNnNnNN.............',
      7: 'PkPTTTTTTTTTnnnnnnnnnnnnnnnnnN.',
      8: 'PPPTnTTTTTTnnnnnnnnnnnnnnnnnnN.',
      9: '.QQnnnTTTnnnnnnnnnnnnnnnnnnnNNn',
    }),
    fps: 3,
    hp: 30,
    moves: [
      { id: 'gore', name: 'TUSK GORE', intent: 'attack', dmg: 8, weight: 2 },
      { id: 'snort', name: 'SNORT AND PAW', intent: 'charge', weight: 2, after: 'stampede' },
      { id: 'stampede', name: 'STAMPEDE', intent: 'attack', dmg: 24, weight: 0 },
      { id: 'dig', name: 'DIG FOR SHINIES', intent: 'steal', dmg: 3, steal: 5, weight: 1 },
    ],
    xp: 15,
    shinies: 6,
    colors: [0xd6a77a, 0x8f563b, 0xf5a5b8],
  },
];
