// Machines family: the city's junk learned to walk (and roll, and hover). Stage 25 on.
import type { EnemyDef } from '../types';
import { frames } from './art';

const DRONE = [
  'lllll.........lllll.',
  '..d.............d...',
  '.gddg..........gddg.',
  '..d....llllll...d...',
  '..dllllllllllllld...',
  '...lwwlllllllllgg...',
  '..lgCCgggggggggggd..',
  '..lCkcggggrggggggd..',
  '...gggddddddddddd...',
  '....d.d......d.d....',
  '...dd.........dd....',
];

const VACUUM = [
  '..........k..........',
  '.........kr..........',
  '........k............',
  '....llllllllllll.....',
  '..llwwlllllllllllg...',
  '.lllBBBBBBlllllllgg..',
  '.llBCBCBBBlllllllgg..',
  'lllBBBBBBllllllggggd.',
  'bbbbbbbbbbbbbbbbbbbbb',
  'ggggggggggCyyCggggddd',
  '.ddOdOdddddddddddddd.',
  '..OdO.....dd....dd...',
];

const CRAB = [
  '...........l.l.l..........',
  '..........lllllll.........',
  '.........llgdddgll........',
  '.........lgdkkkdgl........',
  '...r.r...lgdkkdgll........',
  'yyy.l.l.yyyyyyyyyyyy......',
  'yOOOglgyyOOOOOOOOOOOy.....',
  '....OOyOOOOOOOOOOOOOOS....',
  'yOOOOOOOOkOOOOOkOOOOOSS...',
  '.OOOSOOOOOOOOOOOOOOOOSS...',
  '..SS..SOOOOOOOOOOOOSSS....',
  '.......SSSSSSSSSSSSS......',
  '.......k.k.k..k.k.k.......',
  '......k..k..k..k..k.k.....',
  '.....k..k...k...k...k.....',
];

const TURRET = [
  '..........llll......',
  '........lllllllg....',
  '.......llwwlllllg...',
  '......llllllllllgg..',
  'ddddddllqrrlllllgg..',
  'aaaaaalqyqrllllggg..',
  'ddddddllqrrlllllgg..',
  '......lllllllllggg..',
  '.......gggOgOgggg...',
  '..........dgd.......',
  '..........dgd.......',
  '.........ddgdd......',
  '........dd.g.dd.....',
  '.......dd..g..dd....',
  '......dd...g...dd...',
  '.....ddd..ggg..ddd..',
];

const GOLEM = [
  '.........ggggg...............',
  '.......gglllllgg.............',
  '......glllwlllllg............',
  '......glCCllllllgd...........',
  '......glcCllllllgd...........',
  '......gllllllllggd...........',
  '.......gkdkdkdkgd....ddd.....',
  '.......ggggggggd...ddaadd....',
  '....nnnnnnnnnnnnnnndaaaaad...',
  '...noooonnnnnnnnnnndaggaad...',
  '..noUUUonnnUUUUUnnndaggaad...',
  '..nUUUUUnnUUyyUUUnndaaaaad...',
  '..nUUUUUnnUyyyyUUnn.ddadd....',
  '..nnUUUnnnUUyyUUUnn..nUn.....',
  '..gnnnnnnnUUUUUUUnn..nUn.....',
  '.ggg..nnnnnnnnnnnnn..nUn.....',
  'glllg.nnnnnnnnnnnnU..nUn.....',
  'gllggg.UUnnnnnnUUUU..gggg....',
  'gglgdg.UUUUUUUUUUUU.glllgg...',
  '.gggd..ddddddddddd..gllggd...',
  '.......gggg...gggg...gggd....',
  '.......glld...glld...........',
  '.......glld...glld...........',
  '......glllgd.glllgd..........',
  '......ddddd..ddddd...........',
];

export const ENEMIES_MACHINES: EnemyDef[] = [
  {
    id: 'drone',
    name: 'REPAIR DRONE',
    family: 'machines',
    role: 'support',
    minStage: 25,
    frames: frames(DRONE, {
      0: '.lll...........lll..',
      7: '..lCkcggggOggggggd..',
    }),
    fps: 8,
    hp: 24,
    dodge: 0.2,
    flyer: true,
    onDeath: 'burst',
    moves: [
      { id: 'repair', name: 'REPAIR BEAM', intent: 'heal', heal: 0.22, allies: true, weight: 3 },
      { id: 'overclock', name: 'OVERCLOCK', intent: 'buff', buff: { rage: 2 }, allies: true, weight: 1 },
      { id: 'zap', name: 'ZAP', intent: 'attack', dmg: 7, weight: 2 },
    ],
    xp: 14,
    shinies: 5,
    colors: [0x94b0c2, 0x73eff7, 0xb13e53],
  },
  {
    id: 'vacuum_bot',
    name: 'VACUUM BOT',
    family: 'machines',
    role: 'trickster',
    minStage: 25,
    frames: frames(VACUUM, {
      0: '...........k.........',
      1: '..........kr.........',
      2: '.........k...........',
      6: '.llBBBBBBBlllllllgg..',
      10: '.dOdOddddddddddddddd.',
      11: '..dOd.....dd....dd...',
    }),
    fps: 6,
    hp: 24,
    dodge: 0.15,
    moves: [
      { id: 'suck', name: 'SUCK UP SHINIES', intent: 'steal', dmg: 3, steal: 8, weight: 3 },
      { id: 'tangle', name: 'CORD TANGLE', intent: 'debuff', dmg: 3, apDrain: 1, weight: 2 },
      { id: 'bump', name: 'BUMP', intent: 'attack', dmg: 7, weight: 1 },
    ],
    xp: 14,
    shinies: 7,
    colors: [0x94b0c2, 0x3b5dc9, 0xffcd75],
  },
  {
    id: 'gear_crab',
    name: 'GEAR CRAB',
    family: 'machines',
    role: 'guard',
    minStage: 27,
    armor: 4,
    frames: frames(CRAB, {
      0: '..........l.l.l.l.........',
      1: '..........lllllll.........',
      4: '....r.r..lgdkkdgll........',
      5: 'yyy..l.lyyyyyyyyyyyy......',
      12: '.......k..k.k.k..k.k......',
      13: '......k..k.k...k..k.k.....',
    }),
    fps: 3,
    hp: 34,
    moves: [
      { id: 'clamp', name: 'CLAMP DOWN', intent: 'block', block: 15, guard: true, weight: 3 },
      { id: 'pinch', name: 'HYDRAULIC PINCH', intent: 'attack', dmg: 10, weight: 2 },
      { id: 'grind', name: 'GRIND GEARS', intent: 'buff', buff: { thorns: 4 }, weight: 1 },
    ],
    xp: 16,
    shinies: 6,
    colors: [0xffa300, 0xffcd75, 0x94b0c2],
  },
  {
    id: 'turret',
    name: 'TURRET',
    family: 'machines',
    role: 'charger',
    minStage: 28,
    frames: frames(TURRET, {
      4: 'ddddddllrqqlllllgg..',
      5: 'aaaaaalryYqllllggg..',
      6: 'ddddddllrqqlllllgg..',
    }),
    fps: 4,
    hp: 30,
    moves: [
      { id: 'burst', name: 'BURST FIRE', intent: 'multi', dmg: 3, hits: 3, weight: 2 },
      { id: 'lock', name: 'LOCK ON', intent: 'charge', weight: 2, after: 'laser' },
      { id: 'laser', name: 'MEGA LASER', intent: 'attack', dmg: 28, weight: 0 },
      { id: 'flash', name: 'FLASHBANG', intent: 'debuff', apply: { weak: 2 }, apDrain: 1, weight: 1 },
    ],
    xp: 16,
    shinies: 6,
    colors: [0x94b0c2, 0xff4b1f, 0xfff3b0],
  },
  {
    id: 'scrap_golem',
    name: 'SCRAP GOLEM',
    family: 'machines',
    role: 'brute',
    minStage: 30,
    armor: 5,
    frames: frames(GOLEM, {
      3: '......glcCllllllgd...........',
      4: '......glCCllllllgd...........',
      11: '..nUUUUUnnUUOOUUUnndaaaaad...',
      12: '..nUUUUUnnUOyyOUUnn.ddadd....',
      13: '..nnUUUnnnUUOOUUUnn..nUn.....',
    }),
    fps: 2,
    hp: 52,
    moves: [
      { id: 'slam', name: 'SCRAP SLAM', intent: 'attack', dmg: 13, weight: 3 },
      { id: 'grind', name: 'JUNK GRINDER', intent: 'multi', dmg: 5, hits: 3, weight: 2 },
      { id: 'weld', name: 'SELF WELD', intent: 'heal', heal: 0.12, weight: 1 },
    ],
    xp: 16,
    shinies: 7,
    colors: [0x7a4a33, 0x94b0c2, 0xffcd75],
  },
];
