// Spooks family: the things that go bump after dark. Stage 18 on.
import type { EnemyDef } from '../types';
import { frames, frames2 } from './art';

const GHOST = [
  '.....wwwww.......',
  '...wwwwwwwwi.....',
  '..wwwwwwwwwwi....',
  '.wwHHwwHHwwwi....',
  '.wwHtwwHtwwwii...',
  'wwwHHwwHHwwwwi...',
  'wwwwwwwwwwwwwii..',
  'wwwwwHHwwwwwwiii.',
  'wwwwHHHwwwwwwiiiC',
  'iwwwwHwwwwwwiiiCC',
  'iiwwwwwwwwwiiiCC.',
  '.iiwiwwwiwiiiCC..',
  '..ii.iwi.iiCCC...',
  '.....ii...CC.....',
];

const SKELCAT = [
  '..Q.....Q.................',
  '..QQ...QQQ................',
  '..QQQQQQQQ................',
  '.QQHHQQHHQl............Q..',
  '.QQHLQQHLQl...........Q.l.',
  'QQQQQQQQQl.............l..',
  '.QQQkQQQl..............Q..',
  '..QwkwQ.QQQQQQQQQQQQQQl...',
  '...ll...Q.Q.Q.Q.Q.Ql......',
  '.......QQ.Q.Q.Q.Q.Qll.....',
  '.......Q..l.l.l.l.ll......',
  '........QQQQQQQQQQl.......',
  '........Q..Q.....Q..Q.....',
  '........Q..Q.....Q..Q.....',
  '.......Ql.Ql....Ql.Ql.....',
];

const BAT_A = [
  '..........e...e..........',
  'e.........ee.ee.........e',
  'ue........vvvvv........eu',
  'uve......vrerre.......veu',
  '.uve.....eeeeee.....veeu.',
  '.uvve...eewweee....vveu..',
  '..uvvvveeeeeeeeevvvveu...',
  '..uueeeeeeeeeeeeeeeeuu...',
  '...uu.uuueeeeeeuu.u.uu...',
  '.........ueeeeu..........',
  '..........u..u...........',
];
const BAT_B = [
  '.........................',
  '..........e...e..........',
  '..........ee.ee..........',
  '..........vvvvv..........',
  '.........vrerre..........',
  '...vvvvvveeeeeevvvvvv....',
  '..vveeeeeewweeeeeeeevv...',
  '.uveeeeeeeeeeeeeeeeeevu..',
  '.uueeeeeueeeeeeeueeeeuu..',
  'uu.ueeeu.ueeeeu.ueeeu.uu.',
  'u...uuu...u..u...uuu...u.',
];

const PUMPKIN = [
  '..........FF.........',
  '.........FF..........',
  '.....oooooOooooo.....',
  '...ooyooooOoooooUU...',
  '..oyyoooooOooooooUU..',
  '.oyoqqoooqqooooooUUU.',
  '.ooYYqoooYYqoooooUUU.',
  '.oooooooooooooooUUUU.',
  '.oqYYYYYYYYoooooUUUU.',
  '.ooqUqUqUqoooooUUUU..',
  '..oooooooooooUUUUU...',
  '...UUUUUUUUUUUUU.....',
  '.....eeeeeeeee.......',
  '..sSeevveeeeeeee.....',
  '.ssSevveeeeeeeeue....',
  'ssS.eveeeeeeeeuuee...',
  'sS..eveeeeeeeuuuees..',
  '....eeeeeeeeuuuu.ssS.',
  '....eeeeeeeuuuuu..sS.',
  '....euueuuuueuuu.....',
  '.....NN.....NN.......',
  '.....NN.....NN.......',
  '....NNN....NNN.......',
];

const SHEET = [
  '.......QQQQQ.........',
  '.....QQQQQQQQQ.......',
  '....QQQQQQQQQQQ......',
  '...QQHHQQHHQQQTT.....',
  '...QQHyQQHyQQQQTT....',
  '..QQQQQQQQQQQQQTT....',
  '..QQQQQQQQQQQQQQTT...',
  '..QQQTQQQQQTQQQQTT...',
  '.QQQQTQQQQQTQQQQTTT..',
  '.QQQQTQQQQQTQQQQQTT..',
  '.QQQQTQQQQQTQQQQQTTT.',
  '.QQQTQQQQQQQTQQQQTTT.',
  'QQQQTQQQQQQQTQQQQTTTT',
  'QQQTQQQQQQQQQTQQQTTTT',
  'TQQTQQQQQQQQQTQQTTTTJ',
  'TTQTQQQTTQQQQTQTTTJJJ',
  'TTTJTTTJJTTTTJTTJJJ.J',
  '.J..JJ...JJJ..JJ.....',
];

export const ENEMIES_SPOOKS: EnemyDef[] = [
  {
    id: 'ghost',
    name: 'GHOST',
    family: 'spooks',
    role: 'trickster',
    minStage: 18,
    frames: frames(GHOST, {
      11: '.iiwiwwwiwiiiC....',
      12: '..ii.iwi.iiCC.....',
      13: '...........CC.....',
      7: 'wwwwwwwwwwwwwiii.',
      8: 'wwwwwHwwwwwwwiiiC',
      9: 'iwwwwwwwwwwwiiiCC',
    }),
    fps: 3,
    hp: 22,
    dodge: 0.35,
    flyer: true,
    moves: [
      { id: 'boo', name: 'BOO!', intent: 'debuff', apply: { weak: 2 }, apDrain: 1, weight: 2 },
      { id: 'chill', name: 'CHILL TOUCH', intent: 'attack', dmg: 7, weight: 2 },
      { id: 'haunt', name: 'HAUNT POCKETS', intent: 'steal', dmg: 3, steal: 6, weight: 1 },
    ],
    xp: 14,
    shinies: 5,
    colors: [0xf4f4f4, 0x73eff7, 0xc7f2ff],
  },
  {
    id: 'skeleton_cat',
    name: 'SKELETON CAT',
    family: 'spooks',
    role: 'charger',
    minStage: 19,
    onDeath: 'revive',
    frames: frames(SKELCAT, {
      3: '.QQHHQQHHQl.............',
      4: '.QQHHQQHHQl...........Q..',
      5: 'QQQQQQQQQl...........Q.l.',
      6: '.QQQkQQQl.............l..',
    }),
    fps: 3,
    hp: 24,
    moves: [
      { id: 'rattle', name: 'BONE RATTLE', intent: 'debuff', apply: { vuln: 2 }, weight: 1 },
      { id: 'claw', name: 'BONE CLAW', intent: 'multi', dmg: 4, hits: 2, weight: 2 },
      { id: 'arch', name: 'ARCH BACK', intent: 'charge', weight: 2, after: 'pounce' },
      { id: 'pounce', name: 'GRAVE POUNCE', intent: 'attack', dmg: 22, weight: 0 },
    ],
    xp: 15,
    shinies: 5,
    colors: [0xfff6e0, 0x94b0c2, 0xa7f070],
  },
  {
    id: 'bat',
    name: 'BAT',
    family: 'spooks',
    role: 'support',
    minStage: 18,
    frames: frames2(BAT_A, BAT_B),
    fps: 8,
    hp: 18,
    dodge: 0.25,
    flyer: true,
    moves: [
      { id: 'screech', name: 'NIGHT SCREECH', intent: 'buff', buff: { rage: 2 }, allies: true, weight: 2 },
      { id: 'drink', name: 'SHARE BLOOD', intent: 'heal', heal: 0.2, allies: true, weight: 2 },
      { id: 'bite', name: 'FANG BITE', intent: 'attack', dmg: 5, apply: { weak: 1 }, weight: 2 },
    ],
    xp: 12,
    shinies: 4,
    colors: [0x7a4a8f, 0x3b1f5c, 0xb13e53],
  },
  {
    id: 'pumpkin_head',
    name: 'PUMPKIN HEAD',
    family: 'spooks',
    role: 'brute',
    minStage: 20,
    onDeath: 'burst',
    frames: frames(PUMPKIN, {
      5: '.oyoYYoooYYooooooUUU.',
      6: '.ooYyYoooYyYoooooUUU.',
      8: '.oYYYYYYYYYoooooUUUU.',
      9: '.ooYUYUYUYoooooUUUU..',
    }),
    fps: 3,
    hp: 46,
    moves: [
      { id: 'smash', name: 'GOURD SMASH', intent: 'attack', dmg: 12, weight: 3 },
      { id: 'flail', name: 'STRAW FLAIL', intent: 'multi', dmg: 5, hits: 2, weight: 2 },
      { id: 'cackle', name: 'CACKLE', intent: 'buff', buff: { rage: 3 }, weight: 1 },
    ],
    xp: 16,
    shinies: 6,
    colors: [0xef7d57, 0xffcd75, 0x5d275d],
  },
  {
    id: 'haunted_sheet',
    name: 'HAUNTED SHEET',
    family: 'spooks',
    role: 'guard',
    minStage: 19,
    regen: 3,
    frames: frames(SHEET, {
      0: '........QQQQQ........',
      1: '......QQQQQQQQ.......',
      2: '....QQQQQQQQQQQ......',
      4: '...QQHHQQHHQQQQTT....',
      17: '..J..JJ...JJJ..JJ....',
    }),
    fps: 2,
    hp: 30,
    moves: [
      { id: 'wrap', name: 'WRAP UP', intent: 'block', block: 14, guard: true, weight: 3 },
      { id: 'flap', name: 'FLAP', intent: 'attack', dmg: 7, weight: 2 },
      { id: 'call', name: 'CALL THE BATS', intent: 'summon', summon: 'bat', weight: 1, once: true },
    ],
    xp: 14,
    shinies: 5,
    colors: [0xfff6e0, 0xd6a77a, 0x86745a],
  },
];
