// Strays family: bigger four-legged trouble from the edge of town. Stage 3 on.
import type { EnemyDef } from '../types';
import { frames } from './art';

const DOG = [
  '......TTTT..................',
  '....TTTTTTnNN...............',
  '...TTTTTTTnNNN..............',
  '...TTTTTTTnNNN...........Tn.',
  '..TTkwTTTnnNNN...........Tn.',
  '..TTkkTTTnnNNN..........Tn..',
  'kTTTTTTTTnnNNnTTTTTTTTTTTn..',
  'TTTTTTTTnnnnNnnnnnnnnnnnnn..',
  'TTTTTTTnnnnnnnnnnnnnnnnnnn..',
  '.kwkwkknlrlrlnnnnnnnnnnnnN..',
  '.RRRRknnrryrrnnnnnnnnnnnnN..',
  '..nnnnnnnrrnnnnnnnnnnnnnNN..',
  '....nnnnnnnnnnnnnnnnnnnNN...',
  '.....nnnnnnnNNNNNNNnnnnNN...',
  '.....nnNnnNN.....NnnNnnN....',
  '.....nnNnnN......NnnNnnN....',
  '.....nnNnnN......NnnNnnN....',
  '....QQQ.QQQ.....QQQ.QQQ.....',
];

const FOX = [
  '..k...k......................',
  '..ok.ok......................',
  '..ooooo......................',
  '.yyooooo.....................',
  '.yykyoooo................ooo.',
  'kyyyyyoooo.............oooooo',
  '.wwwwwooooooooooooooooooooooo',
  '..wwwwooooooooooooooooooooUww',
  '...wwwooooooooooooooooUUUwwww',
  '...wwwwoooooooooooooooUU.www.',
  '....wwwoooooooooooooUUU......',
  '.....oUUoUUUUUUUUoUUU........',
  '.....dd.dd.......dd.dd.......',
  '.....dd.dd.......dd.dd.......',
  '....ddk.ddk.....ddk.ddk......',
];

const BADGER = [
  '.....wwwww...................',
  '...ddwwwwwddlllllllll........',
  '..dddwwwwwddllllllllllll.....',
  '.wddkdwwwddglllllllllllll....',
  'wwwddwwwwgggggggggggggglll...',
  'kwwwwwwwggggggggggggggggggl..',
  '.wwwwwdddgggggggggggggggggg..',
  '..ww.dddddggggggggggggggggdd.',
  '.....dddddddddgggggggggddddd.',
  '.....dddddddddddddddddddddd..',
  '.....ddd.ddd.......ddd.ddd...',
  '....QdQd.QdQd.....QdQd.QdQ...',
];

const SKUNK = [
  '.................aaa...',
  '...............aawwwa..',
  '..............awwwllaa.',
  '..............awwlaaaaa',
  '...............alaaaaaa',
  '..a.a...........aaaaad.',
  '.aaaa............aaaad.',
  '.awaa.wwwwwwwww..aaaad.',
  'aakawwwwwlllllwwwaadd..',
  'Paaaaawllaaaaallwaad...',
  '.aaaaaaaaaaaaaaaaadd...',
  '..aaaaaaaaaaaaaaddd....',
  '...ddddddddddddddd.....',
  '...dd.dd....dd.dd......',
];

const COYOTE = [
  '..S..S.......................',
  '..SS.SS......................',
  '..sSSsS......................',
  '.sssssSS.....................',
  '.sskYsSSS....................',
  'ssssssSSS...................S',
  'kssQQSSSSSSSSSSSSSSSSSSS..SSS',
  '.QQQQSSSSSSSSSSSSSSSSSSSSSSSj',
  '..QQQSSSSSSSSSSSSSSSSSSSSjjj.',
  '...QQQSSSSSSSSSSSSSSSSSSjj...',
  '....QQSSSQQQQQQQSSSSSSSj.....',
  '.....SSjSj.......SSjSSj......',
  '.....SS.Sj.......SS.Sj.......',
  '.....SS.Sj.......SS.Sj.......',
  '....QQj.QQj.....QQj.QQj......',
];

export const ENEMIES_STRAYS: EnemyDef[] = [
  {
    id: 'dog',
    name: 'GUARD DOG',
    family: 'strays',
    role: 'brute',
    minStage: 4,
    frames: frames(DOG, {
      3: '...TTTTTTTnNNN............Tn',
      4: '..TTkwTTTnnNNN............Tn',
      5: '..TTkkTTTnnNNN...........Tn.',
      10: '.RRPPknnrryrrnnnnnnnnnnnnN..',
      11: '..PPnnnnnrrnnnnnnnnnnnnnNN..',
    }),
    fps: 3,
    hp: 32,
    moves: [
      { id: 'bite', name: 'BITE', intent: 'attack', dmg: 8, weight: 3 },
      { id: 'maul', name: 'MAUL', intent: 'multi', dmg: 4, hits: 2, weight: 2 },
      { id: 'growl', name: 'GROWL', intent: 'buff', buff: { rage: 2 }, weight: 1 },
    ],
    xp: 12,
    shinies: 4,
    colors: [0x8f563b, 0xd6a77a, 0xb13e53],
  },
  {
    id: 'fox',
    name: 'SLY FOX',
    family: 'strays',
    role: 'trickster',
    minStage: 3,
    frames: frames(FOX, {
      4: '.yykyoooo.................ooo',
      5: 'kyyyyyoooo..............oooooo',
      7: '..wwwwoooooooooooooooooooooooUw',
      8: '...wwwooooooooooooooooUUUwwww.',
      9: '...wwwwoooooooooooooooUU..ww..',
    }),
    fps: 3,
    hp: 15,
    dodge: 0.25,
    moves: [
      { id: 'nip', name: 'NIP', intent: 'attack', dmg: 4, weight: 2 },
      { id: 'swipe', name: 'PICKPOCKET', intent: 'steal', dmg: 2, steal: 5, weight: 2 },
      { id: 'trick', name: 'FEINT', intent: 'debuff', apply: { vuln: 2 }, weight: 1 },
    ],
    xp: 9,
    shinies: 5,
    colors: [0xef7d57, 0xf4f4f4, 0xffcd75],
  },
  {
    id: 'badger',
    name: 'BADGER',
    family: 'strays',
    role: 'guard',
    minStage: 4,
    frames: frames(BADGER, {
      1: '...ddwwwwwddllllllllll.......',
      2: '..dddwwwwwddlllllllllllll....',
      3: '.wddkdwwwddgllllllllllllll...',
      11: '....QdQd..QdQd....QdQd.QdQ...',
    }),
    fps: 2,
    hp: 24,
    moves: [
      { id: 'dig', name: 'DIG IN', intent: 'block', block: 10, guard: true, weight: 3 },
      { id: 'claw', name: 'CLAW', intent: 'attack', dmg: 5, weight: 2 },
      { id: 'bristle', name: 'BRISTLE', intent: 'buff', buff: { thorns: 2 }, weight: 1 },
    ],
    xp: 11,
    shinies: 4,
    colors: [0x94b0c2, 0xf4f4f4, 0x333c57],
  },
  {
    id: 'skunk',
    name: 'SKUNK',
    family: 'strays',
    role: 'support',
    minStage: 3,
    frames: frames(SKUNK, {
      0: '..................aaa..',
      1: '................aawwwa.',
      2: '...............awwwllaa',
      7: '.aaaa.wwwwwwwww..aaaad.',
    }),
    fps: 3,
    hp: 16,
    moves: [
      { id: 'spray', name: 'SPRAY', intent: 'debuff', apply: { poison: 4 }, weight: 2 },
      { id: 'rally', name: 'STINK RALLY', intent: 'buff', buff: { rage: 2 }, allies: true, weight: 2 },
      { id: 'lick', name: 'LICK WOUNDS', intent: 'heal', heal: 0.15, allies: true, weight: 1 },
      { id: 'nip', name: 'NIP', intent: 'attack', dmg: 3, weight: 1 },
    ],
    xp: 10,
    shinies: 4,
    colors: [0x434b68, 0xf4f4f4, 0xa7f070],
  },
  {
    id: 'coyote',
    name: 'COYOTE',
    family: 'strays',
    role: 'charger',
    minStage: 5,
    frames: frames(COYOTE, {
      4: '.sskksSSS....................',
      5: 'ssssssSSS....................',
      6: 'kssQQSSSSSSSSSSSSSSSSSSS...SS',
    }),
    fps: 3,
    hp: 22,
    moves: [
      { id: 'snap', name: 'SNAP', intent: 'attack', dmg: 6, weight: 2 },
      { id: 'howl', name: 'HOWL', intent: 'charge', weight: 2, after: 'lunge' },
      { id: 'lunge', name: 'MOON LUNGE', intent: 'attack', dmg: 17, weight: 0 },
      { id: 'circle', name: 'CIRCLE', intent: 'debuff', apply: { weak: 1 }, weight: 1 },
    ],
    xp: 11,
    shinies: 4,
    colors: [0xb88a4a, 0xe8c170, 0xfff6e0],
  },
];
