// Street family: the alley regulars. Stage 1 on.
import type { EnemyDef } from '../types';
import { frames, frames2 } from './art';

const RAT = [
  '......gg............',
  '.....gPPg..ggggg....',
  '.....gPPgglllllggg..',
  '...gglllllllllllggg.',
  '..gllkllllllllllgggg',
  'Pglllllllllggggggggg..P',
  '.gllgggggggggggaaaaaa.P',
  '..allaaaaaaaaaaaaaPPP.',
  '...PP..P....PP..P.....',
];

const PIGEON_A = [
  '.........ll.........',
  '........llll........',
  '.......lllgl........',
  '..lll..llgd.........',
  '.llwll.lgd..........',
  'Pllkll.lllllllll....',
  '.lllDDlllllllllgg...',
  '..lDDtlllllllggggd..',
  '...lDllllllgggdddd..',
  '....llllggggg.......',
  '......P.P...........',
];
const PIGEON_B = [
  '....................',
  '....................',
  '....................',
  '..lll...............',
  '.llwll..............',
  'Pllkll.lllllllll....',
  '.lllDDllgggggllgg...',
  '..lDDtllgdddgggggd..',
  '...lDlllgdddgddddd..',
  '....llllggddg.......',
  '......P.P.gd........',
];

const POSSUM = [
  '..lll......................',
  '.lgggd.....................',
  'lgdddgd..dd................',
  'lgggggd.dPd..lllllllll.....',
  'lgdddgd.dddllllllllllllll..',
  'lgggggd.wwwwlllllllllllllg.',
  'lgdddgdwwkwwlllllllllllggg.',
  'lgglggPwwwwwllllllgggggggg.',
  'lgdddgd.wwwglllllggggggggd...PP',
  'lgggggd..wlggggggggggggddd..P..',
  'lgdddgd...gggggggggddddddPPP...',
  'lgggggd...ddddddddddddd........',
  'lgdddgd....PP..PP...PP..PP.....',
  '.lgggd.........................',
  '..ddd..........................',
];

const CROW_A = [
  '...........aa........',
  '..........aBBa.......',
  '.........aBIIa.......',
  '..dd....aBIda........',
  '.dddd..aBIdd.........',
  'ldwkd.aBIdddddd......',
  'yldddddddddddddd.....',
  '.ddddddddddddddaa....',
  '..daaddddddaaaaaaaa..',
  '...aaaaaaaaa...aa.aa.',
  '.....l.l.............',
];
const CROW_B = [
  '.....................',
  '.....................',
  '.....................',
  '..dd.................',
  '.dddd................',
  'ldwkd..ddddddd.......',
  'yldddddBBBBBdddd.....',
  '.dddddBIIIIIaddaa....',
  '..daadBIddaaaaaaaaa..',
  '...aaadIdaaa...aa.aa.',
  '.....l.lIda..........',
  '........aa...........',
];

const CAT = [
  '..o.....o.....................',
  '..oo...ooo.................yo.',
  '..yPo.oyPo.................oo.',
  '..yyyoyyyoo................oU.',
  '.yyyyyyyyyoo...............oU.',
  '.yLkyyyLkyooo.............oU..',
  'yyLkyyyLkyoooo............oU..',
  'PyyyyyyyyooooooyyoyyoyyoooU...',
  '.yyQkQyyoooooooyoyyoyyoooooU..',
  '..yQQQyooooooUoooUoooUoooooU..',
  '...yQyoooooooUoooUoooUooooUU..',
  '....ooooQQQoooooooooooooooU...',
  '....oooQQQQQooooooooooooUU....',
  '....oUoQQQQoooUUUUUoooUUoU....',
  '....oUoUUooUUU...UoUUoUoUU....',
  '....oUoU..oU.....oU..oUoU.....',
  '....QQ.QQ.QQ.....QQ..QQQQ.....',
];

export const ENEMIES_STREET: EnemyDef[] = [
  {
    id: 'rat',
    name: 'RAT',
    family: 'street',
    role: 'brute',
    minStage: 1,
    frames: frames(RAT, {
      0: '.....gg..............',
      1: '....gPPg...ggggg.....',
      5: 'Pglllllllllggggggggg.P.',
      6: '.gllgggggggggggaaaaaaP.',
    }),
    fps: 4,
    hp: 12,
    moves: [
      { id: 'bite', name: 'BITE', intent: 'attack', dmg: 4, weight: 3 },
      { id: 'gnaw', name: 'GNAW', intent: 'multi', dmg: 2, hits: 2, weight: 2 },
      { id: 'frenzy', name: 'FRENZY', intent: 'buff', buff: { rage: 1 }, weight: 1 },
    ],
    xp: 4,
    shinies: 2,
    colors: [0x94b0c2, 0x566c86, 0xf5a5b8],
  },
  {
    id: 'pigeon',
    name: 'PIGEON',
    family: 'street',
    role: 'support',
    minStage: 1,
    frames: frames2(PIGEON_A, PIGEON_B),
    fps: 6,
    hp: 14,
    dodge: 0.2,
    flyer: true,
    moves: [
      { id: 'peck', name: 'PECK PECK', intent: 'multi', dmg: 2, hits: 2, weight: 3 },
      { id: 'crumbs', name: 'SHARE CRUMBS', intent: 'heal', heal: 0.2, allies: true, weight: 2 },
      { id: 'coo', name: 'COO', intent: 'debuff', apply: { weak: 1 }, weight: 1 },
    ],
    xp: 4,
    shinies: 2,
    colors: [0x94b0c2, 0xf4f4f4, 0x257179],
  },
  {
    id: 'possum',
    name: 'POSSUM',
    family: 'street',
    role: 'guard',
    minStage: 2,
    frames: frames(POSSUM, {
      6: 'lgdddgdwwkwwllllllllllllggg.',
      5: 'lgggggd.wwwwlllllllllllllgg.',
      8: 'lgdddgd.wwwglllllggggggggd..PP.',
      9: 'lgggggd..wlggggggggggggddd.P...',
    }),
    fps: 3,
    hp: 20,
    onDeath: 'revive',
    moves: [
      { id: 'shield', name: 'LID SHIELD', intent: 'block', block: 9, guard: true, weight: 3 },
      { id: 'bite', name: 'BITE', intent: 'attack', dmg: 4, weight: 2 },
      { id: 'hiss', name: 'HISS', intent: 'debuff', apply: { weak: 1 }, weight: 1 },
    ],
    xp: 10,
    shinies: 4,
    colors: [0x94b0c2, 0xf4f4f4, 0xf5a5b8],
  },
  {
    id: 'crow',
    name: 'CROW',
    family: 'street',
    role: 'trickster',
    minStage: 3,
    frames: frames2(CROW_A, CROW_B),
    fps: 6,
    hp: 14,
    dodge: 0.15,
    flyer: true,
    moves: [
      { id: 'peck', name: 'PECK', intent: 'attack', dmg: 4, weight: 2 },
      { id: 'caw', name: 'CAW', intent: 'debuff', apply: { weak: 2 }, weight: 1 },
      { id: 'snatch', name: 'SNATCH', intent: 'steal', dmg: 2, steal: 4, weight: 2 },
    ],
    xp: 8,
    shinies: 4,
    colors: [0x333c57, 0x29366f, 0xffcd75],
  },
  {
    id: 'cat',
    name: 'ALLEY CAT',
    family: 'street',
    role: 'charger',
    minStage: 3,
    frames: frames(CAT, {
      0: '..o.....o......................',
      1: '..oo...ooo.....................',
      2: '..yPo.oyPo...................yo',
      3: '..yyyoyyyoo..................oo',
      4: '.yyyyyyyyyoo................oU.',
      5: '.ykkyyykkyooo..............oU..',
      6: 'yyyyyyyyyyoooo.............oU..',
    }),
    fps: 3,
    hp: 18,
    moves: [
      { id: 'scratch', name: 'SCRATCH', intent: 'attack', dmg: 5, weight: 2 },
      { id: 'hiss', name: 'HISS', intent: 'debuff', apply: { vuln: 1 }, weight: 1 },
      { id: 'crouch', name: 'CROUCH', intent: 'charge', weight: 2, after: 'pounce' },
      { id: 'pounce', name: 'POUNCE', intent: 'attack', dmg: 15, weight: 0 },
    ],
    xp: 9,
    shinies: 3,
    colors: [0xef7d57, 0xffcd75, 0x7a4a33],
  },
];
