// Swamp family: things with wet feet and wetter mouths. Stage 8 on.
import type { EnemyDef } from '../types';
import { frames } from './art';

const FROG = [
  '...GGG..............',
  '..GLLLG.............',
  '.GLYkYG.............',
  '.LLYYYGGGGGG........',
  'LLLLLLLLLLLLGGG.....',
  'LLLLLLLLLLLLLGGG....',
  'kkkkkkLLLLLLLLGGG...',
  'YYYYYkGLLLLLLLGGGG..',
  '.YYYYYGGLLLLLGGLLGF.',
  '..YYYYGGGGLLGGLLLLGF',
  '...LGGGGGGGGGLLLLGGF',
  '...LGFGGGGGGGLLLLGFF',
  '..LGFF.FFFFFFLLGGGF.',
  '.LGGG..GGGGGGGGFFF..',
];

const GATOR = [
  '.......zz.........................',
  '......zykz.....z.z.z.z.z..........',
  '..zzzzGGGGzzzzGzGzGzGzGzz.........',
  '.GGGGGGGGGGGGGGGGGGGGGGGGzzz......',
  'GGGGGGGGGFGGGGGGGGGGGGGGGGGGGzzz..',
  'wkwkwkwkFFGGGGGGGGGGGGGGGGGGGGGGzz',
  'RRRRRRRRFFFYYYYYYYYYYYYYFFFFFFFF..',
  '.wkwkwkwFFYYYYYYYYYYYYFFFF........',
  '..FFFFFFFFFFFFFFFFFFFFFF..........',
  '.........FFzF......FFzF...........',
  '........FFzF......FFzF............',
  '.......zzzz......zzzz.............',
];

const LEECH = [
  '.......eeeeee.......',
  '.....eevvvvvvee.....',
  '....evvMvvvvMvve....',
  '...evvvMvvvvMvvve...',
  '..evvvveeeeeevvvve..',
  '.eYvve.......evvvee.',
  'hekve.........evveu.',
  'hhve...........euuu.',
  '.hh.............uu..',
];

const HERON = [
  '.......kk.............',
  '......wwwkk...........',
  '.....wwwwl.kk.........',
  'yyyyyOkwww............',
  '..OOOOwwww............',
  '......www.............',
  '......lww.............',
  '.....lww..............',
  '.....lw...............',
  '.....lww..............',
  '......lww.............',
  '......lwll............',
  '.....wlllllc..........',
  '....wllgggggll........',
  '....wlgggggggglll.....',
  '....wlgggggggggggll...',
  '.....lggddggggggggglll',
  '.....lgggdddgggggggddd',
  '......lgggdddddgddddd.',
  '.......ggggddddd......',
  '..........dd..........',
  '..........S...........',
  '..........S...........',
  '..........S...........',
  '.........SS...........',
  '..........S...........',
  '..........S...........',
  '..........S...........',
  '........SSSS..........',
];

const TURTLE = [
  '...........EEE..EEE..EEE.........',
  '.........EEzzzEEzzzEEzzzEE.......',
  '.......EEzmmzzEzzzzEzzzzzEE......',
  '......EzzmzzzEzzzzzzEzzzzzzE.....',
  '.....EzzzzzzEzzzzzzzzEzzzzzzE....',
  '.....EFFFFFEFFFFFFFFFEFFFFFFFE...',
  '..JJJJjFFFFEFFFFFFFFFEFFFFFFFFE..',
  '.JJyJJjjEEEEEEEEEEEEEEEEEEEEEEj..',
  'JJYkJJJJjjjjjjjjjjjjjjjjjjjjjjjj.',
  'kkJJJJJJJSSSSSSSSSSSSSSSSSSSSjJJJ',
  'JkkJJJJ.JJSJJ.........JJSJJ...JJ.',
  '.JJJ....JJSJJ.........JJSJJ......',
  '........kJkJk.........kJkJk......',
];

export const ENEMIES_SWAMP: EnemyDef[] = [
  {
    id: 'frog',
    name: 'BULLFROG',
    family: 'swamp',
    role: 'support',
    minStage: 8,
    frames: frames(FROG, {
      7: 'YYYYYkGLLLLLLLGGGG..',
      8: 'YYYYYYGGLLLLLGGLLGF.',
      9: 'YYYYYYGGGGLLGGLLLLGF',
      10: '.YYYYGGGGGGGGLLLLGGF',
      2: '.GLLLLG.............',
    }),
    fps: 2,
    hp: 18,
    moves: [
      { id: 'croak', name: 'CROAK CHORUS', intent: 'buff', buff: { rage: 2 }, allies: true, weight: 2 },
      { id: 'mud', name: 'MUD BATH', intent: 'heal', heal: 0.2, allies: true, weight: 2 },
      { id: 'tongue', name: 'TONGUE LASH', intent: 'attack', dmg: 5, apply: { weak: 1 }, weight: 2 },
    ],
    xp: 11,
    shinies: 4,
    colors: [0xa7f070, 0x38b764, 0xfff3b0],
  },
  {
    id: 'gator',
    name: 'GATOR',
    family: 'swamp',
    role: 'brute',
    minStage: 9,
    frames: frames(GATOR, {
      1: '......zkkz.....z.z.z.z.z..........',
      4: 'GGGGGGGGGFGGGGGGGGGGGGGGGGGGGzzzzz',
      5: 'wkwkwkwkFFGGGGGGGGGGGGGGGGGGGGGGG.',
    }),
    fps: 2,
    hp: 34,
    moves: [
      { id: 'chomp', name: 'CHOMP', intent: 'attack', dmg: 9, weight: 3 },
      { id: 'tailwhip', name: 'TAIL WHIP', intent: 'multi', dmg: 4, hits: 2, weight: 2 },
      { id: 'submerge', name: 'SUBMERGE', intent: 'block', block: 12, weight: 1, after: 'roll' },
      { id: 'roll', name: 'DEATH ROLL', intent: 'attack', dmg: 16, weight: 0 },
    ],
    xp: 14,
    shinies: 5,
    colors: [0x38b764, 0x2d6a3e, 0xfff3b0],
  },
  {
    id: 'leech',
    name: 'LEECH',
    family: 'swamp',
    role: 'trickster',
    minStage: 8,
    frames: frames(LEECH, {
      0: '....................',
      1: '.......eeeeee.......',
      2: '....eevvMvvvMvee....',
      3: '..eevvvMvvvvMvvvee..',
      4: '.evvvveeeeeeeevvvve.',
    }),
    fps: 2,
    hp: 17,
    regen: 3,
    moves: [
      { id: 'suck', name: 'SUCK', intent: 'attack', dmg: 4, apDrain: 1, weight: 2 },
      { id: 'numb', name: 'NUMBING SLIME', intent: 'debuff', apply: { weak: 2, vuln: 1 }, weight: 2 },
      { id: 'leech', name: 'LEECH SHINIES', intent: 'steal', dmg: 2, steal: 5, weight: 1 },
    ],
    xp: 11,
    shinies: 5,
    colors: [0x7a4a8f, 0xc0398e, 0x3b1f5c],
  },
  {
    id: 'heron',
    name: 'HERON',
    family: 'swamp',
    role: 'charger',
    minStage: 10,
    frames: frames(HERON, {
      0: '........kk............',
      1: '.......wwwkk..........',
      2: '......wwwwl.kk........',
      3: '.yyyyyOkwww...........',
      4: '...OOOOwwww...........',
      5: '.......www............',
      6: '.......lww............',
      7: '......lww.............',
    }),
    fps: 2,
    hp: 24,
    dodge: 0.1,
    moves: [
      { id: 'jab', name: 'BEAK JAB', intent: 'attack', dmg: 6, weight: 2 },
      { id: 'aim', name: 'TAKE AIM', intent: 'charge', weight: 2, after: 'spear' },
      { id: 'spear', name: 'SPEAR STAB', intent: 'attack', dmg: 19, apply: { vuln: 1 }, weight: 0 },
      { id: 'splash', name: 'WING SPLASH', intent: 'debuff', apply: { weak: 1 }, weight: 1 },
    ],
    xp: 12,
    shinies: 4,
    colors: [0x94b0c2, 0xf4f4f4, 0xffcd75],
  },
  {
    id: 'snapping_turtle',
    name: 'SNAPPING TURTLE',
    family: 'swamp',
    role: 'guard',
    minStage: 11,
    armor: 2,
    frames: frames(TURTLE, {
      7: '..JyJJjjEEEEEEEEEEEEEEEEEEEEEEj..',
      8: '.JYkJJJJjjjjjjjjjjjjjjjjjjjjjjjj.',
      9: 'kkJJJJJJJSSSSSSSSSSSSSSSSSSSSjJJJ',
      10: '.kkJJJJ.JJSJJ.........JJSJJ...JJ.',
      11: '..JJ....JJSJJ.........JJSJJ......',
    }),
    fps: 2,
    hp: 26,
    moves: [
      { id: 'shell', name: 'SHELL WALL', intent: 'block', block: 12, guard: true, weight: 3 },
      { id: 'snap', name: 'SNAP', intent: 'attack', dmg: 7, weight: 2 },
      { id: 'spikes', name: 'SPIKY SHELL', intent: 'buff', buff: { thorns: 3 }, weight: 1 },
    ],
    xp: 13,
    shinies: 5,
    colors: [0x6a8f3a, 0x86745a, 0x16382c],
  },
];
