// Void family: whatever leaks in from past the edge of the sky. Stage 35 on.
import type { EnemyDef } from '../types';
import { frames, frames2 } from './art';

const GRUB = [
  '...mmmmm......................',
  '..mttttmmmmmm.mmmmm...........',
  '.mttMttttttttmtttttmmmmm......',
  'mtMMMttttttttDtttttDttttmmm...',
  'mtMkMtttttttDtttttDtttttDttmm.',
  'ttMMMtttttttDtttttDtttttDttttm',
  'tttttttttttDtttttDtttttDtttttD',
  'kkkkktttttDtttttDtttttDttttDDA',
  'RhhhRkttttDtttttDtttttDtttDDA.',
  'kRRRkAAAADAAAAADAAAAADAAAAAA..',
  '.AAAA.A..A..A..A..A..A..AA....',
];

const JELLY_A = [
  '......hhhhhh......',
  '....hhPPhhhhhh....',
  '...hPPhhhhhhhhh...',
  '..hPhhhhYhhhhhhM..',
  '..hhhhhYYYhhhhhM..',
  '.hhhYYYYYYYYYhhMM.',
  '.hhhhYYYYYYYhhhMM.',
  '.hkhhhYYYYYhhhMMM.',
  '.hkhhYYhhhYYhhMMM.',
  '.MMMMYhMMMMhYMMMM.',
  '.MMMMMMMMMMMMMMMM.',
  '..v..v..v..v..v...',
  '..v...v.v.v..v....',
  '...v..v..v...v....',
  '...v.v...v..v.....',
  '..v..v..v...v.....',
  '..v...v..v...v....',
  '...v..v..v...v....',
];
const JELLY_B = [
  '..................',
  '......hhhhhh......',
  '....hhPPhhhhhh....',
  '...hPPhhhhYhhhh...',
  '..hPhhhhYYYhhhhM..',
  '.hhhhYYYYYYYYYhMM.',
  '.hhhhhYYYYYYYhhMM.',
  '.hkhhhhYYYYYhhMMM.',
  '.hkhhhYYhhhYYhMMM.',
  'MMMMMYMMMMMMMYMMMM',
  '.MMMMMMMMMMMMMMMM.',
  '...v..v..v..v..v..',
  '..v..v..v...v..v..',
  '..v..v...v..v...v.',
  '...v..v..v...v..v.',
  '...v...v..v..v..v.',
  '..v...v..v..v..v..',
  '..................',
];

const EYESTALK = [
  '....wwwww.....',
  '..wwwwwwwll...',
  '.wwwwwwwwwll..',
  'wwMMwwwwwwwl..',
  'wMkkMwwrwwwll.',
  'wMkkMwwwrwwll.',
  'wwMMwwwwwrwll.',
  '.wwwwwwwwwll..',
  '..lwwwwwlll...',
  '....lllll.....',
  '.....vve......',
  '.....vve......',
  '....vvee......',
  '....vve.......',
  '...vvee.......',
  '...vve........',
  '...vvee.......',
  '....vvee......',
  '....vvvee.....',
  '..vvvvveeee...',
  '.vvvvvveeeeeu.',
  'vvveevveeeeeuu',
  'uu.uu.uuu.uuu.',
];

const VOID_COON = [
  '.......kk....kk...................',
  '......kuMk..kMuk..................',
  '......kuMekkeMuk..................',
  '.....keeeeeeeeeek.................',
  '....keeeeeYeeeeeek................',
  '...keCCeeeeeeeCCeek.......kkkk....',
  '...kCuuuueeeekuuuek......keeeek...',
  '...kuukCkuuuukCkuek.....kuuuuuuk..',
  '.kkvuuuuuuuuuuuuuek.....keeeeeek..',
  'kCvvvvvCeeeuuuuueek.....kuuuuuuuk.',
  '.kkvvvvvvveeeeeeek......keeeeeeek.',
  '..kkkvvvveeeeeeeekk.....kuuuuuuuk.',
  '.....kkkkeeeeeeeeeekk...keeYeeek..',
  '......keeeeeeeeeeeeeekkkuuuuuuuk..',
  '.....keeYeeeeeeeeeeeYeeeeeeeeek...',
  '.....keeeevvvvvvvveeeeeYeeeuuk....',
  '......kevvvvvvvvvvvveeeeeeeek.....',
  '.....keevvvvvvvvvvvveeeeeeeek.....',
  '......keevvvvvvvvvvveeeeeeeek.....',
  '.......keevvvvvvvvveeeeeeeek......',
  '......keeeeeeeYeeeeeeeeeeeek......',
  '.......keeeeeeeekkkkkeeeeek.......',
  '.......kuuukeuuuk....kkuuuk.......',
  '.......kuuukkuuuk.....kuuuk.......',
  '........kkkk.kkkk......kkkk.......',];

const IMP = [
  '..R....R..............',
  '..RR..RR..............',
  '..yyyyyy.....o........',
  '.yyYyyyyo..oo.....o...',
  'yyYkyYkyoooqoo..oo....',
  'yyyyyyyyoqqqoooooo..o.',
  'yyRRRRyyoqqqqqoooooo..',
  '.yyRRyyooqqqqqqoooooo.',
  '.oyyyyooqqqqqqqqRRoo..',
  '..ooooooqqqqqqRRRR.o..',
  '...qqqqqqqqRRRR.......',
  '....RRRRRRR...........',
];

export const ENEMIES_VOID: EnemyDef[] = [
  {
    id: 'alien_grub',
    name: 'ALIEN GRUB',
    family: 'void',
    role: 'brute',
    minStage: 35,
    armor: 3,
    regen: 4,
    frames: frames(GRUB, {
      0: '...............................',
      1: '...mmmmm.mmmmm.mmmmm...........',
      2: '..mttMtmttttttmtttttmmmmm......',
      8: 'RhhhRkttttDtttttDtttttDtttDDA.',
    }),
    fps: 2,
    hp: 54,
    moves: [
      { id: 'chomp', name: 'GRINDER MAW', intent: 'attack', dmg: 13, weight: 3 },
      { id: 'acid', name: 'ACID SPIT', intent: 'debuff', dmg: 6, apply: { vuln: 2, poison: 3 }, weight: 2 },
      { id: 'molt', name: 'MOLT', intent: 'block', block: 16, weight: 1 },
    ],
    xp: 16,
    shinies: 6,
    colors: [0x5fd3c9, 0x9be2b0, 0xc0398e],
  },
  {
    id: 'star_jelly',
    name: 'STAR JELLY',
    family: 'void',
    role: 'support',
    minStage: 35,
    regen: 4,
    frames: frames2(JELLY_A, JELLY_B, 'kv'),
    fps: 3,
    hp: 28,
    dodge: 0.15,
    flyer: true,
    moves: [
      { id: 'glow', name: 'STARLIGHT', intent: 'heal', heal: 0.25, allies: true, weight: 3 },
      { id: 'twinkle', name: 'TWINKLE', intent: 'buff', buff: { rage: 2, thorns: 2 }, allies: true, weight: 1 },
      { id: 'sting', name: 'NEBULA STING', intent: 'attack', dmg: 7, apply: { stun: 1 }, weight: 1 },
    ],
    xp: 16,
    shinies: 6,
    colors: [0xff77c8, 0xfff3b0, 0xb05ccf],
  },
  {
    id: 'eye_stalk',
    name: 'EYE STALK',
    family: 'void',
    role: 'guard',
    minStage: 37,
    armor: 3,
    frames: frames(EYESTALK, {
      3: 'wwwwwwwwwwwl..',
      4: 'wllllwwrwwwll.',
      5: 'wkkkkwwwrwwll.',
      6: 'wwwwwwwwwrwll.',
      12: '.....vvee.....',
      13: '.....vve......',
    }),
    fps: 2,
    hp: 38,
    moves: [
      { id: 'stare', name: 'STARE DOWN', intent: 'block', block: 16, guard: true, weight: 3 },
      { id: 'beam', name: 'EYE BEAM', intent: 'attack', dmg: 11, weight: 2 },
      { id: 'hatch', name: 'HATCH GRUB', intent: 'summon', summon: 'alien_grub', weight: 1, once: true },
    ],
    xp: 16,
    shinies: 6,
    colors: [0xf4f4f4, 0xb05ccf, 0xc0398e],
  },
  {
    id: 'void_raccoon',
    name: 'VOID RACCOON',
    family: 'void',
    role: 'trickster',
    minStage: 38,
    frames: frames(VOID_COON, {
      7: '...kuukkkuuuukkkuek.....kuuuuuuk..',
      4: '....keeeeeeeeeeeeek..............',
      12: '.....kkkkeeeeeeeeeekk...keeeeeek..',
      14: '.....keeeeeeeeeeeeeYeeeeYeeeek...',
    }),
    fps: 2,
    hp: 27,
    dodge: 0.3,
    moves: [
      { id: 'mirror', name: 'MIRROR SWIPE', intent: 'attack', dmg: 9, weight: 2 },
      { id: 'pilfer', name: 'VOID PILFER', intent: 'steal', dmg: 5, steal: 10, weight: 2 },
      { id: 'warp', name: 'WARP TIME', intent: 'debuff', apDrain: 2, apply: { weak: 1 }, weight: 1 },
    ],
    xp: 16,
    shinies: 7,
    colors: [0x7a4a8f, 0x73eff7, 0xfff3b0],
  },
  {
    id: 'comet_imp',
    name: 'COMET IMP',
    family: 'void',
    role: 'charger',
    minStage: 36,
    onDeath: 'burst',
    frames: frames(IMP, {
      2: '..yyyyyy....o.........',
      3: '.yyYyyyyo..o..o...o...',
      5: 'yyyyyyyyoqqqooooo..o..',
      9: '..ooooooqqqqqqRRRRo...',
    }),
    fps: 6,
    hp: 30,
    dodge: 0.2,
    flyer: true,
    moves: [
      { id: 'scorch', name: 'SCORCH', intent: 'attack', dmg: 8, apply: { poison: 2 }, weight: 2 },
      { id: 'orbit', name: 'WIDE ORBIT', intent: 'charge', weight: 2, after: 'impact' },
      { id: 'impact', name: 'COMET IMPACT', intent: 'attack', dmg: 30, weight: 0 },
      { id: 'cackle', name: 'HOT CACKLE', intent: 'buff', buff: { rage: 2 }, weight: 1 },
    ],
    xp: 16,
    shinies: 6,
    colors: [0xff4b1f, 0xffcd75, 0xef7d57],
  },
];
