// Wastes family: survivors of the frozen flats and the hot sand. Stage 10 on.
import type { EnemyDef } from '../types';
import { frames, frames2 } from './art';

const PENGUIN = [
  '....aaaa......',
  '...aaddda.....',
  '..adwkddda....',
  'OOOadddddda...',
  '.Oyydddddda...',
  '..ywwdddddd...',
  '..wwwwdddddd..',
  '.wwwwwwddddd..',
  '.wwwwwwdadddd.',
  '.wwwwwwdaaddd.',
  '.wwwwwwldaadd.',
  '.lwwwwwlldaadd',
  '.lwwwwwllddaa.',
  '..lwwwllldd...',
  '..llllllddd...',
  '...OOO..OOO...',
];

const HARE = [
  '.....k.k..........',
  '....wl.wl.........',
  '....wl.wl.........',
  '....wPlwP.........',
  '....wPlwPl........',
  '...wwwwwwl........',
  '..wwwwwwwl........',
  '.wwkwwwwwwl.......',
  'Pwwwwwwwwwil......',
  '.iiwwwwwwwwwwi....',
  '..iiwwwwwwwwwwil..',
  '...wwwwwwwwwwwiil.',
  '...wwiwwwwwwwwiiww',
  '...wiiwwwwwwwiilww',
  '...ii.iwwwwwwiil..',
  '..iii.iiiiiilll...',
];

const SCORPION = [
  '................SSSS.......',
  '..............SsssssS......',
  '.............rS.....sS.....',
  '............rr.......sS....',
  '.....................sS....',
  '......................sS...',
  '......................sS...',
  '.....................ssS...',
  '.sss................ssS....',
  'ss..s.............sssS.....',
  's.......skksssssssSS......',
  'sss...ssssssssssssssS.....',
  '.sSSSsssssssssssssSSn.....',
  '..SSSSSssssssssssSSnn.....',
  '....SSSSSSSSSSSSSSnn......',
  '.....nnSnnSnnSnnSn........',
  '....k.k.k.k.k.k.k.k.......',
  '...k.k.k.k.k.k.k.k........',
];

const VULTURE_A = [
  '...........nN.nN.nN........',
  '..........nnNnnNnnN........',
  '.........nnnnnnnnnN........',
  '........nnnnnnnnnN.........',
  '.......nnnnnnnnnN..........',
  '..PP...NnnnnnnnN...........',
  '.PPPP..NNnnnnNN............',
  'lPkPP.QQNNNNNNNNNNNN.......',
  'llPPPQQQNNNNNNNNNNNNNNN....',
  '.l.PQQQNNNNNNNNNNNNNNNNNNN.',
  '....QQNNNNNNNNNNNNNNNjjjNNN',
  '......NNNNNNNNNNNNNNj..jjN.',
  '........NNNNNNNNNN.........',
  '.........OO..OO............',
  '...........................',
  '...........................',
];
const VULTURE_B = [
  '...........................',
  '...........................',
  '...........................',
  '...........................',
  '...........................',
  '..PP.......................',
  '.PPPP......................',
  'lPkPP.QQNNNNNNNNNNNN.......',
  'llPPPQQQNNnnnnnnnNNNNNN....',
  '.l.PQQQNNnnnnnnnnnNNNNNNNN.',
  '....QQNNNnnnnnnnnnNNNjjjNNN',
  '......NNNNnnnnnnnnNNj..jjN.',
  '........NNNnnnnnnnNN.......',
  '.........NNnnnnnnN.........',
  '..........NnN.nN.nN........',
  '..........N...N...N........',
];

const YETI = [
  '.......iiiii..........',
  '.....iiwwwwwii........',
  '....iwwwwwwwwwi.......',
  '...iwwccccwwwwwi......',
  '...wwcBccBcwwwwwi.....',
  '...wcckcckccwwwwi.....',
  '...wccccccccwwwwi.....',
  '...wcwkwwkwcwwwwii....',
  '....wcRRRRcwwwwwwii...',
  '..iiwwccccwwwwwwwwii..',
  '.iwwwwwwwwwwwwwwwwwii.',
  'iwwwiwwwwwwwwwwwwwwwil',
  'iwwiiwwwwwwwwwwwwwwiil',
  'iwwi.iwwwwwwwwwwwwwiil',
  'iwwi.iwwwwwwwwwwwwiill',
  'iiil.iiwwwwwwwwwwiiill',
  'cccl.iiiiwwwwwwiiiill.',
  'cccc.iiiiiiiiiiiiilll.',
  '.cc..iiiiilll.iiilll..',
  '.....iiilll...iilll...',
  '.....ccccc....ccccc...',
];

export const ENEMIES_WASTES: EnemyDef[] = [
  {
    id: 'penguin',
    name: 'PENGUIN',
    family: 'wastes',
    role: 'guard',
    minStage: 10,
    frames: frames(PENGUIN, {
      8: '.wwwwwwdaddddd',
      9: '.wwwwwwdaadddda',
      10: '.wwwwwwldaadd..',
      11: '.lwwwwwlldaad..',
      2: '..adkkddda....',
    }),
    fps: 2,
    hp: 24,
    moves: [
      { id: 'huddle', name: 'HUDDLE', intent: 'block', block: 12, guard: true, weight: 3 },
      { id: 'slap', name: 'FLIPPER SLAP', intent: 'attack', dmg: 6, weight: 2 },
      { id: 'slide', name: 'BELLY SLIDE', intent: 'attack', dmg: 4, apply: { stun: 1 }, weight: 1 },
    ],
    xp: 12,
    shinies: 4,
    colors: [0xf4f4f4, 0x333c57, 0xffa300],
  },
  {
    id: 'snow_hare',
    name: 'SNOW HARE',
    family: 'wastes',
    role: 'trickster',
    minStage: 10,
    frames: frames(HARE, {
      0: '...................',
      1: '.....k.k...........',
      2: '....wl.wl..........',
      3: '....wPlwP..........',
      4: '....wPlwPl.........',
      8: 'Pwwwwwwwwwil.......',
    }),
    fps: 3,
    hp: 16,
    dodge: 0.35,
    moves: [
      { id: 'kick', name: 'THUMP KICK', intent: 'attack', dmg: 5, weight: 2 },
      { id: 'dash', name: 'SNATCH AND DASH', intent: 'steal', dmg: 2, steal: 6, weight: 2 },
      { id: 'snow', name: 'KICK UP SNOW', intent: 'debuff', dmg: 2, apDrain: 1, weight: 1 },
    ],
    xp: 11,
    shinies: 6,
    colors: [0xf4f4f4, 0xc7f2ff, 0xf5a5b8],
  },
  {
    id: 'scorpion',
    name: 'SCORPION',
    family: 'wastes',
    role: 'charger',
    minStage: 12,
    armor: 2,
    frames: frames(SCORPION, {
      0: '.................SSSS......',
      1: '...............SsssssS.....',
      2: '..............rS....sS.....',
      3: '.............rr......sS....',
      8: '.ss.................ssS....',
      9: 's..s..............sssS.....',
      10: 's.s.....skksssssssSS......',
    }),
    fps: 2,
    hp: 22,
    moves: [
      { id: 'pinch', name: 'PINCH', intent: 'multi', dmg: 3, hits: 2, weight: 2 },
      { id: 'raise', name: 'RAISE TAIL', intent: 'charge', weight: 2, after: 'sting' },
      { id: 'sting', name: 'VENOM STING', intent: 'attack', dmg: 18, apply: { poison: 3 }, weight: 0 },
      { id: 'burrow', name: 'BURROW', intent: 'block', block: 8, weight: 1 },
    ],
    xp: 13,
    shinies: 5,
    colors: [0xe8c170, 0xb88a4a, 0xb13e53],
  },
  {
    id: 'vulture',
    name: 'VULTURE',
    family: 'wastes',
    role: 'support',
    minStage: 11,
    frames: frames2(VULTURE_A, VULTURE_B),
    fps: 3,
    hp: 20,
    dodge: 0.1,
    flyer: true,
    moves: [
      { id: 'circle', name: 'CIRCLE OVERHEAD', intent: 'buff', buff: { rage: 2 }, allies: true, weight: 2 },
      { id: 'scraps', name: 'SHARE SCRAPS', intent: 'heal', heal: 0.2, allies: true, weight: 2 },
      { id: 'peck', name: 'PICK AT', intent: 'attack', dmg: 5, apply: { vuln: 1 }, weight: 2 },
    ],
    xp: 12,
    shinies: 5,
    colors: [0x5c3a2e, 0x4d3b24, 0xf5a5b8],
  },
  {
    id: 'yeti_cub',
    name: 'YETI CUB',
    family: 'wastes',
    role: 'brute',
    minStage: 13,
    armor: 2,
    frames: frames(YETI, {
      7: '...wckwwwwkcwwwwii....',
      8: '....wcwRRwcwwwwwwii...',
      15: 'iiil.iiwwwwwwwwwwiiill',
      16: 'cccl.iiiiwwwwwwiiiill.',
      17: 'cccc.iiiiiiiiiiiiilll.',
    }),
    fps: 2,
    hp: 40,
    moves: [
      { id: 'smash', name: 'SNOWBALL SMASH', intent: 'attack', dmg: 10, weight: 3 },
      { id: 'tantrum', name: 'TANTRUM', intent: 'multi', dmg: 4, hits: 3, weight: 2 },
      { id: 'roar', name: 'TINY ROAR', intent: 'debuff', apply: { weak: 2 }, weight: 1 },
    ],
    xp: 15,
    shinies: 5,
    colors: [0xf4f4f4, 0xc7f2ff, 0x41a6f6],
  },
];
