// Pixel maps. One character per pixel, '.' is transparent, other keys come from PAL.
// Rows shorter than the widest row are padded on the right.

export const RACCOON_0 = [
  '..kk........kk..',
  '.kgdk......kdgk.',
  '.kggkkkkkkkkggk.',
  'kggggggggggggggk',
  'kgwwwggggggwwwgk',
  'kkkkkkwggwkkkkkk',
  'kkkwkkkggkkkwkkk',
  '.kkkkgwwwwgkkkk.',
  '..kggwwwwwwggk..',
  '...kkwwkkwwkk...',
  '....kkkkkkkk..kk',
  '...kgglllggk.kgk',
  '...kgllllllgkdk.',
  '...kgllllllgkgk.',
  '....kggggggkkk..',
  '....kk....kk....',
];

export const RACCOON_1 = [
  ...RACCOON_0.slice(0, 10),
  '....kkkkkkkk.kk.',
  '...kgglllggkkgk.',
  '...kgllllllgkdk.',
  '...kgllllllgkgk.',
  '....kggggggkk...',
  '.....kk..kk.....',
];

// Facing down: enemies walk toward the raccoon.
export const RAT_0 = [
  '....P.....',
  '.....P....',
  '....kk....',
  '..knnnnk..',
  '.knnnnnnk.',
  '.knnnnnnk.',
  'kPknnnnkPk',
  '.knrnnrnk.',
  '..knnnnk..',
  '...kPPk...',
];
export const RAT_1 = [
  '.....P....',
  '....P.....',
  '....kk....',
  '..knnnnk..',
  '.knnnnnnk.',
  'kknnnnnnkk',
  'kPknnnnkPk',
  '.knrnnrnk.',
  '..knnnnk..',
  '...kPPk...',
];

export const PIGEON_0 = [
  '...kk..kk...',
  '....kllk....',
  '..kklllkkk..',
  '.kllgllgllk.',
  'klllkllklllk',
  'kkk.kllk.kkk',
  '....klgk....',
  '....kGDk....',
  '.....kk.....',
  '.....yy.....',
];
export const PIGEON_1 = [
  '...kk..kk...',
  '....kllk....',
  '...kllllk...',
  '..kllgglk...',
  '..kllllllk..',
  '...kkllkk...',
  '....klgk....',
  '....kGDk....',
  '.....kk.....',
  '.....yy.....',
];

export const CAT_0 = [
  '.kk......kk.',
  'kyok....koyk',
  'kooooooooook',
  'koonooooonok',
  'koGkooookGok',
  'koooooPooook',
  '.koowkkwook.',
  '..kooooook..',
  '.kononnonok.',
  '.kooooooook.',
  '.kooooooookk',
  '..kk....kk..',
];
export const CAT_1 = [
  ...CAT_0.slice(0, 10),
  '.kooooooook.',
  '...kk..kk...',
];

export const CROW_0 = [
  '....kkkk....',
  '.....kk.....',
  'kk..kddk..kk',
  'kgkkddddkkgk',
  '.kdgddddgdk.',
  '..kkddddkk..',
  '....kddk....',
  '....krrk....',
  '.....yy.....',
];
export const CROW_1 = [
  '....kkkk....',
  '.....kk.....',
  '....kddk....',
  '...kddddk...',
  '..kddddddk..',
  '.kgkddddkgk.',
  '..k.kddk.k..',
  '....krrk....',
  '.....yy.....',
];

export const DOG_0 = [
  '..kk......kk..',
  '.kNNk....kNNk.',
  '.kNnkkkkkknNk.',
  '..knnnnnnnnk..',
  '.knnnnnnnnnnk.',
  '.knkwknnkwknk.',
  '.knnnnnnnnnnk.',
  '.knwwwkkwwwnk.',
  '.kwwwkkkkwwwk.',
  '..kwwkrrkwwk..',
  '..kkwwwwwwkk..',
  '.knnnnnnnnnnk.',
  '.knnnnnnnnnnk.',
  '.kk..kkkk..kk.',
];
export const DOG_1 = [
  ...DOG_0.slice(0, 12),
  '.knnnnnnnnnnk.',
  '..kk.k..k.kk..',
];

export const VAN_0 = [
  '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
  '.kwwwwwwwwwwwwwwwwwwwwwwwwwwwwk.',
  'kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwk',
  'kwlwwwwwwwwwwwwwwwwwwwwwwwwwwlwk',
  'kwlwwwwwwwwwwwwwwwwwwwwwwwwwwlwk',
  'kwlwwwwkkkwwwwwwwwwwwwkkkwwwwlwk',
  'kwlwwwkgggkwwwwwwwwwwkgggkwwwlwk',
  'kwlwwwwkkkwwwwwwwwwwwwkkkwwwwlwk',
  'kwlwwwwwwwwwwwwwwwwwwwwwwwwwwlwk',
  'kwlwwwwwwwwwkkkkkkkkwwwwwwwwwlwk',
  'kwlwwwwwwwwkrrrrkbbbbkwwwwwwwlwk',
  'kwlwwwwwwwwkrrrrkbbbbkwwwwwwwlwk',
  'kwlwwwwwwwwwkkkkkkkkwwwwwwwwwlwk',
  'kwrrrrrrrrrrrrrrrrrrrrrrrrrrrrwk',
  'kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwk',
  'kkBBBBBBBBBBBBBBBBBBBBBBBBBBBBkk',
  'kBBcBBBBBBBBBBBBBBBBBBBBBBBBBBBk',
  'kBcBBBBBBBBBBBBBBBBBBBBBBBBBBBBk',
  'kBBBBBBBBBBBBBBBBBBBBBBBBBBBBcBk',
  'kkwwwwwwwwwwwwwwwwwwwwwwwwwwwwkk',
  'kwyyywwwwwkkkkkkkkkkkwwwwwyyywk.',
  'kwyyywwwwwkdkdkdkdkdkwwwwwyyywk.',
  'kgggggggggggggggggggggggggggggggk',
  '.kkk.....................kkk....',
];
// Second frame swaps the siren colours.
export const VAN_1 = VAN_0.map((row, i) =>
  i === 10 || i === 11 ? row.replace('rrrr', '@@@@').replace('bbbb', 'rrrr').replace('@@@@', 'bbbb') : row,
);

export const RATKING_0 = [
  '.....y...yy...y.....',
  '.....yy.yyyy.yy.....',
  '.....yyyyrryyyy.....',
  '...kkyyyyyyyyyykk...',
  '..kPknnnnnnnnnnkPk..',
  '..kPknnnnnnnnnnkPk..',
  '.kkknnnnnnnnnnnnkkk.',
  '.knnnnnnnnnnnnnnnnk.',
  'knnrrrnnnnnnnnrrrnnk',
  'knnnrknnnnnnnnkrnnnk',
  'knnnnnnnnnnnnnnnnnnk',
  'knnnnnnnPPPPnnnnnnnk',
  '.knnnnnPkkkkPnnnnk..',
  '.knnnnnnwkkwnnnnnnk.',
  '..knnnnnnnnnnnnnnk..',
  '..knnlllllllllnnnk..',
  '.knnllllllllllllnnk.',
  '.knnllllllllllllnnk.',
  '..knnnnnnnnnnnnnk...',
  '..kkk..kk..kk..kkk..',
  '.........PP.........',
  '..........PP........',
];
export const RATKING_1 = [
  ...RATKING_0.slice(0, 19),
  '...kkk.kk..kk.kkk...',
  '..........PP........',
  '.........PP.........',
];

export const PEBBLE = [
  '.ll.',
  'lwwl',
  'lwwl',
  '.ll.',
];

export const ORB = [
  '.kkk.',
  'krrrk',
  'krPrk',
  'krrrk',
  '.kkk.',
];

export const FEATHER = [
  '.k.',
  'kPk',
  'kPk',
  'krk',
  'krk',
  '.k.',
];

export const NET = [
  'kkkkk',
  'kowok',
  'kwowk',
  'kowok',
  'kkkkk',
];

export const CAN = [
  '.kkkkkkkk.',
  'kllllllllk',
  'kggggggggk',
  '.kkkkkkkk.',
  '.kglglglk.',
  '.kglglglk.',
  '.kglglglk.',
  '.kglglglk.',
  '.kglglglk.',
  '.kglglglk.',
  '.kgggggggk',
  '..kkkkkk..',
];

export const COIN_0 = [
  '.kkk.',
  'kyyyk',
  'kywyk',
  'kyyyk',
  '.kkk.',
];
export const COIN_1 = [
  '.kk.',
  'kyyk',
  'kwyk',
  'kyyk',
  '.kk.',
];
export const COIN_2 = [
  'k.',
  'yk',
  'yk',
  'yk',
  'k.',
].map((r) => '.' + r + '.');

export const PIZZA = [
  'kkkkkkk',
  'knnnnnk',
  'kyryyrk',
  '.kyyrk.',
  '.kyyyk.',
  '..kyk..',
  '...k...',
];

export const HEART = [
  '.kk.kk.',
  'krrkrrk',
  'krwrrrk',
  'krrrrrk',
  '.krrrk.',
  '..krk..',
  '...k...',
];
export const HEART_EMPTY = [
  '.kk.kk.',
  'kddkddk',
  'kdddddk',
  'kdddddk',
  '.kdddk.',
  '..kdk..',
  '...k...',
];

export const CAP = [
  '.kkk.',
  'kyyyk',
  'kywyk',
  'kyyok',
  '.kkk.',
];

// 9x9 upgrade icons.
export const ICONS: Record<string, string[]> = {
  rapid: [
    '..k...k..',
    '.kgk.kgk.',
    '.kgk.kgk.',
    'kk.kkk.kk',
    'kgkkgkkgk',
    '.kkgggkk.',
    '.kgggggk.',
    '.kgggggk.',
    '..kkkkk..',
  ],
  twin: [
    '.........',
    '.ll...ll.',
    'lwwl.lwwl',
    'lwwl.lwwl',
    '.ll...ll.',
    '..k...k..',
    '..k...k..',
    '...k.k...',
    '....k....',
  ],
  heavy: [
    '.kkkkkkk.',
    'kllllllk.',
    'kggggggk.',
    '.kglglk..',
    '.kglglk..',
    '.kglglk..',
    '.kglglk..',
    '.kggggk..',
    '..kkkk...',
  ].map((r) => '.' + r.slice(0, 8)),
  pierce: [
    '....k....',
    '...kwk...',
    '..kwwwk..',
    '...kwk...',
    '.ccccccc.',
    '...kwk...',
    '...kwk...',
    '...kwk...',
    '....k....',
  ],
  side: [
    'k.......k',
    '.k.....k.',
    '..k...k..',
    '...kwk...',
    '..kwwwk..',
    '...kwk...',
    '.........',
    '.........',
    '.........',
  ],
  heart: [
    '.........',
    '.kk...kk.',
    'krrk.krrk',
    'krwrkrrrk',
    'krrrrrrrk',
    '.krrrrrk.',
    '..krrrk..',
    '...krk...',
    '....k....',
  ],
  snack: [
    'kkkkkkkkk',
    'knnnnnnnk',
    'kyyryyryk',
    '.kyyyyyk.',
    '.kyryyyk.',
    '..kyyyk..',
    '..kyyrk..',
    '...kyk...',
    '....k....',
  ],
  speed: [
    '.........',
    '....kkk..',
    '...kooyk.',
    'kk.koyyk.',
    '..kkooyk.',
    'kkk.kkk..',
    '...kok...',
    '..kok....',
    '..kk.....',
  ],
  dashcd: [
    '..kkkkk..',
    '.kwwwwwk.',
    'kwwwkwwwk',
    'kwwwkwwwk',
    'kwwwkkkwk',
    'kwwwwwwwk',
    'kwwwwwwwk',
    '.kwwwwwk.',
    '..kkkkk..',
  ],
  shock: [
    '..kkkkk..',
    '.k.....k.',
    'k..kkk..k',
    'k.kCCCk.k',
    'k.kCwCk.k',
    'k.kCCCk.k',
    'k..kkk..k',
    '.k.....k.',
    '..kkkkk..',
  ],
  magnet: [
    '.kkkkkkk.',
    'krrrrrrrk',
    'krrkkkrrk',
    'krrk.krrk',
    'krrk.krrk',
    'kwwk.kwwk',
    'kwwk.kwwk',
    '.kk...kk.',
    '.........',
  ],
  orbit: [
    '...kkk...',
    '..kywyk..',
    '.k.kkk.k.',
    'k.......k',
    'k.......k',
    'k.......k',
    '.k.....k.',
    '..kkkkk..',
    '.........',
  ],
  crit: [
    '....k....',
    '...kyk...',
    'kkkkykkkk',
    'kyyyyyyyk',
    '.kyyyyyk.',
    '..kyyyk..',
    '.kyykyyk.',
    '.kyk.kyk.',
    '.kk...kk.',
  ],
  rage: [
    '....k....',
    '...krk...',
    '..krrok..',
    '.krrooyk.',
    'krroyyyok',
    'krooyyyok',
    'kroyywyok',
    '.krooyyk.',
    '..kkkkk..',
  ],
  vamp: [
    '.kk...kk.',
    'krrk.krrk',
    'krrrkrrrk',
    '.krrrrrk.',
    '..krrrk..',
    '...krk...',
    '..kwkwk..',
    '..kw.wk..',
    '...k.k...',
  ],
};

// 3x5 glyphs for the HUD font.
export const GLYPHS: Record<string, string[]> = {
  A: ['.#.', '#.#', '###', '#.#', '#.#'],
  B: ['##.', '#.#', '##.', '#.#', '##.'],
  C: ['.##', '#..', '#..', '#..', '.##'],
  D: ['##.', '#.#', '#.#', '#.#', '##.'],
  E: ['###', '#..', '##.', '#..', '###'],
  F: ['###', '#..', '##.', '#..', '#..'],
  G: ['.##', '#..', '#.#', '#.#', '.##'],
  H: ['#.#', '#.#', '###', '#.#', '#.#'],
  I: ['###', '.#.', '.#.', '.#.', '###'],
  J: ['..#', '..#', '..#', '#.#', '.#.'],
  K: ['#.#', '#.#', '##.', '#.#', '#.#'],
  L: ['#..', '#..', '#..', '#..', '###'],
  M: ['#.#', '###', '###', '#.#', '#.#'],
  N: ['##.', '#.#', '#.#', '#.#', '#.#'],
  O: ['.#.', '#.#', '#.#', '#.#', '.#.'],
  P: ['##.', '#.#', '##.', '#..', '#..'],
  Q: ['.#.', '#.#', '#.#', '##.', '.##'],
  R: ['##.', '#.#', '##.', '#.#', '#.#'],
  S: ['.##', '#..', '.#.', '..#', '##.'],
  T: ['###', '.#.', '.#.', '.#.', '.#.'],
  U: ['#.#', '#.#', '#.#', '#.#', '###'],
  V: ['#.#', '#.#', '#.#', '#.#', '.#.'],
  W: ['#.#', '#.#', '###', '###', '#.#'],
  X: ['#.#', '#.#', '.#.', '#.#', '#.#'],
  Y: ['#.#', '#.#', '.#.', '.#.', '.#.'],
  Z: ['###', '..#', '.#.', '#..', '###'],
  '0': ['###', '#.#', '#.#', '#.#', '###'],
  '1': ['.#.', '##.', '.#.', '.#.', '###'],
  '2': ['##.', '..#', '.#.', '#..', '###'],
  '3': ['##.', '..#', '.#.', '..#', '##.'],
  '4': ['#.#', '#.#', '###', '..#', '..#'],
  '5': ['###', '#..', '##.', '..#', '##.'],
  '6': ['.##', '#..', '###', '#.#', '###'],
  '7': ['###', '..#', '.#.', '.#.', '.#.'],
  '8': ['###', '#.#', '###', '#.#', '###'],
  '9': ['###', '#.#', '###', '..#', '##.'],
  ' ': ['...', '...', '...', '...', '...'],
  '.': ['...', '...', '...', '...', '.#.'],
  ',': ['...', '...', '...', '.#.', '#..'],
  '!': ['.#.', '.#.', '.#.', '...', '.#.'],
  '?': ['##.', '..#', '.#.', '...', '.#.'],
  ':': ['...', '.#.', '...', '.#.', '...'],
  '-': ['...', '...', '###', '...', '...'],
  '+': ['...', '.#.', '###', '.#.', '...'],
  '%': ['#.#', '..#', '.#.', '#..', '#.#'],
  '/': ['..#', '..#', '.#.', '#..', '#..'],
  "'": ['.#.', '.#.', '...', '...', '...'],
  '(': ['.#.', '#..', '#..', '#..', '.#.'],
  ')': ['.#.', '..#', '..#', '..#', '.#.'],
  '<': ['..#', '.#.', '#..', '.#.', '..#'],
  '>': ['#..', '.#.', '..#', '.#.', '#..'],
  '=': ['...', '###', '...', '###', '...'],
  x: ['...', '#.#', '.#.', '#.#', '...'],
  '*': ['#.#', '.#.', '###', '.#.', '#.#'],
  '#': ['#.#', '###', '#.#', '###', '#.#'],
};
