// Small props, UI icons and the HUD font. Character sprites live in sprites.ts.

export const CAN = [
  '.kkkkkkkk.',
  'kllllllllk',
  'kggggggggk',
  '.kkkkkkkk.',
  '.kglglglk.',
  '.kglglglk.',
  '.kglglglk.',
  '.kglglglk.',
  '.kglglglk.',
  '.kglglglk.',
  '.kgggggggk',
  '..kkkkkk..',
];

export const COIN_0 = [
  '.kkk.',
  'kyyyk',
  'kywyk',
  'kyyyk',
  '.kkk.',
];
export const COIN_1 = [
  '.kk.',
  'kyyk',
  'kwyk',
  'kyyk',
  '.kk.',
];
export const COIN_2 = [
  'k.',
  'yk',
  'yk',
  'yk',
  'k.',
].map((r) => '.' + r + '.');

export const PIZZA = [
  'kkkkkkk',
  'knnnnnk',
  'kyryyrk',
  '.kyyrk.',
  '.kyyyk.',
  '..kyk..',
  '...k...',
];

export const HEART = [
  '.kk.kk.',
  'krrkrrk',
  'krwrrrk',
  'krrrrrk',
  '.krrrk.',
  '..krk..',
  '...k...',
];
export const HEART_EMPTY = [
  '.kk.kk.',
  'kddkddk',
  'kdddddk',
  'kdddddk',
  '.kdddk.',
  '..kdk..',
  '...k...',
];

export const CAP = [
  '.kkk.',
  'kyyyk',
  'kywyk',
  'kyyok',
  '.kkk.',
];

// 9x9 upgrade icons.
export const ICONS: Record<string, string[]> = {
  rapid: [
    '..k...k..',
    '.kgk.kgk.',
    '.kgk.kgk.',
    'kk.kkk.kk',
    'kgkkgkkgk',
    '.kkgggkk.',
    '.kgggggk.',
    '.kgggggk.',
    '..kkkkk..',
  ],
  twin: [
    '.........',
    '.ll...ll.',
    'lwwl.lwwl',
    'lwwl.lwwl',
    '.ll...ll.',
    '..k...k..',
    '..k...k..',
    '...k.k...',
    '....k....',
  ],
  heavy: [
    '.kkkkkkk.',
    'kllllllk.',
    'kggggggk.',
    '.kglglk..',
    '.kglglk..',
    '.kglglk..',
    '.kglglk..',
    '.kggggk..',
    '..kkkk...',
  ].map((r) => '.' + r.slice(0, 8)),
  pierce: [
    '....k....',
    '...kwk...',
    '..kwwwk..',
    '...kwk...',
    '.ccccccc.',
    '...kwk...',
    '...kwk...',
    '...kwk...',
    '....k....',
  ],
  side: [
    'k.......k',
    '.k.....k.',
    '..k...k..',
    '...kwk...',
    '..kwwwk..',
    '...kwk...',
    '.........',
    '.........',
    '.........',
  ],
  heart: [
    '.........',
    '.kk...kk.',
    'krrk.krrk',
    'krwrkrrrk',
    'krrrrrrrk',
    '.krrrrrk.',
    '..krrrk..',
    '...krk...',
    '....k....',
  ],
  snack: [
    'kkkkkkkkk',
    'knnnnnnnk',
    'kyyryyryk',
    '.kyyyyyk.',
    '.kyryyyk.',
    '..kyyyk..',
    '..kyyrk..',
    '...kyk...',
    '....k....',
  ],
  speed: [
    '.........',
    '....kkk..',
    '...kooyk.',
    'kk.koyyk.',
    '..kkooyk.',
    'kkk.kkk..',
    '...kok...',
    '..kok....',
    '..kk.....',
  ],
  dashcd: [
    '..kkkkk..',
    '.kwwwwwk.',
    'kwwwkwwwk',
    'kwwwkwwwk',
    'kwwwkkkwk',
    'kwwwwwwwk',
    'kwwwwwwwk',
    '.kwwwwwk.',
    '..kkkkk..',
  ],
  shock: [
    '..kkkkk..',
    '.k.....k.',
    'k..kkk..k',
    'k.kCCCk.k',
    'k.kCwCk.k',
    'k.kCCCk.k',
    'k..kkk..k',
    '.k.....k.',
    '..kkkkk..',
  ],
  magnet: [
    '.kkkkkkk.',
    'krrrrrrrk',
    'krrkkkrrk',
    'krrk.krrk',
    'krrk.krrk',
    'kwwk.kwwk',
    'kwwk.kwwk',
    '.kk...kk.',
    '.........',
  ],
  orbit: [
    '...kkk...',
    '..kywyk..',
    '.k.kkk.k.',
    'k.......k',
    'k.......k',
    'k.......k',
    '.k.....k.',
    '..kkkkk..',
    '.........',
  ],
  crit: [
    '....k....',
    '...kyk...',
    'kkkkykkkk',
    'kyyyyyyyk',
    '.kyyyyyk.',
    '..kyyyk..',
    '.kyykyyk.',
    '.kyk.kyk.',
    '.kk...kk.',
  ],
  rage: [
    '....k....',
    '...krk...',
    '..krrok..',
    '.krrooyk.',
    'krroyyyok',
    'krooyyyok',
    'kroyywyok',
    '.krooyyk.',
    '..kkkkk..',
  ],
  vamp: [
    '.kk...kk.',
    'krrk.krrk',
    'krrrkrrrk',
    '.krrrrrk.',
    '..krrrk..',
    '...krk...',
    '..kwkwk..',
    '..kw.wk..',
    '...k.k...',
  ],
};

// 7x7 status icons
export const STATUS_ICONS: Record<string, string[]> = {
  poison: ['..k....', '.kLk...', 'kLGLk..', 'kGGGk.k', '.kkk.kL', '.....kG', '......k'],
  weak: ['.kkkkk.', 'kwwwwwk', 'kwkwkwk', 'kwwwwwk', '.kwkwk.', '.kwwwk.', '..kkk..'],
  vuln: ['...k...', '..kok..', '..kok..', '..kok..', '...k...', '..kok..', '...k...'],
  stun: ['y.k.k.y', '.ykyky.', 'kykwkyk', '.ywwwy.', 'kykwkyk', '.ykyky.', 'y.k.k.y'],
  rage: ['...k...', '..krk..', '.krrok.', 'krroyok', 'kroyyok', '.kooyk.', '..kkk..'],
  thorns: ['w.w.w.w', 'kkkkkkk', 'kdldldk', 'kdddddk', 'kdldldk', 'kkkkkkk', 'w.w.w.w'],
  block: ['kkkkkkk', 'klllllk', 'klwlllk', 'klllllk', '.klllk.', '..klk..', '...k...'],
};

// 7x7 intent icons shown over enemies
export const INTENT_ICONS: Record<string, string[]> = {
  attack: ['.....kk', '....kwk', 'k..kwk.', 'kk.wk..', '.kkk...', '.kkk...', 'k..k...'],
  multi: ['...kk.k', '..kwkwk', 'kkwkwk.', 'kwkwk..', '.kkk...', 'kkk....', 'k.k....'],
  block: ['kkkkkkk', 'kbbbbbk', 'kbcbbbk', 'kbbbbbk', '.kbbbk.', '..kbk..', '...k...'],
  buff: ['...k...', '..krk..', '.krrrk.', 'krrrrrk', '..krk..', '..krk..', '..kkk..'],
  debuff: ['..kkk..', '..kvk..', '..kvk..', 'kvvvvvk', '.kvvvk.', '..kvk..', '...k...'],
  heal: ['..kkk..', '..kGk..', 'kkkGkkk', 'kGGGGGk', 'kkkGkkk', '..kGk..', '..kkk..'],
  summon: ['.k...k.', 'kPk.kPk', 'knnknnk', '.kkkkk.', '..kyk..', '.kyyyk.', '..kyk..'],
  charge: ['..kkk..', '..kyk..', '..kyk..', '..kyk..', '..kkk..', '..kyk..', '..kkk..'],
  steal: ['.kkkkk.', 'kyyyyyk', 'kywyyyk', 'kyyyyyk', 'kyyyyyk', '.kkkkk.', '.......'],
  flee: ['...k...', '..kwk..', '.kwwwk.', 'kwwwwwk', '..kwk..', '..kwk..', '..kkk..'],
};

// 3x5 glyphs for the HUD font.
export const GLYPHS: Record<string, string[]> = {
  A: ['.#.', '#.#', '###', '#.#', '#.#'],
  B: ['##.', '#.#', '##.', '#.#', '##.'],
  C: ['.##', '#..', '#..', '#..', '.##'],
  D: ['##.', '#.#', '#.#', '#.#', '##.'],
  E: ['###', '#..', '##.', '#..', '###'],
  F: ['###', '#..', '##.', '#..', '#..'],
  G: ['.##', '#..', '#.#', '#.#', '.##'],
  H: ['#.#', '#.#', '###', '#.#', '#.#'],
  I: ['###', '.#.', '.#.', '.#.', '###'],
  J: ['..#', '..#', '..#', '#.#', '.#.'],
  K: ['#.#', '#.#', '##.', '#.#', '#.#'],
  L: ['#..', '#..', '#..', '#..', '###'],
  M: ['#.#', '###', '###', '#.#', '#.#'],
  N: ['##.', '#.#', '#.#', '#.#', '#.#'],
  O: ['.#.', '#.#', '#.#', '#.#', '.#.'],
  P: ['##.', '#.#', '##.', '#..', '#..'],
  Q: ['.#.', '#.#', '#.#', '##.', '.##'],
  R: ['##.', '#.#', '##.', '#.#', '#.#'],
  S: ['.##', '#..', '.#.', '..#', '##.'],
  T: ['###', '.#.', '.#.', '.#.', '.#.'],
  U: ['#.#', '#.#', '#.#', '#.#', '###'],
  V: ['#.#', '#.#', '#.#', '#.#', '.#.'],
  W: ['#.#', '#.#', '###', '###', '#.#'],
  X: ['#.#', '#.#', '.#.', '#.#', '#.#'],
  Y: ['#.#', '#.#', '.#.', '.#.', '.#.'],
  Z: ['###', '..#', '.#.', '#..', '###'],
  '0': ['###', '#.#', '#.#', '#.#', '###'],
  '1': ['.#.', '##.', '.#.', '.#.', '###'],
  '2': ['##.', '..#', '.#.', '#..', '###'],
  '3': ['##.', '..#', '.#.', '..#', '##.'],
  '4': ['#.#', '#.#', '###', '..#', '..#'],
  '5': ['###', '#..', '##.', '..#', '##.'],
  '6': ['.##', '#..', '###', '#.#', '###'],
  '7': ['###', '..#', '.#.', '.#.', '.#.'],
  '8': ['###', '#.#', '###', '#.#', '###'],
  '9': ['###', '#.#', '###', '..#', '##.'],
  ' ': ['...', '...', '...', '...', '...'],
  '.': ['...', '...', '...', '...', '.#.'],
  ',': ['...', '...', '...', '.#.', '#..'],
  '!': ['.#.', '.#.', '.#.', '...', '.#.'],
  '?': ['##.', '..#', '.#.', '...', '.#.'],
  ':': ['...', '.#.', '...', '.#.', '...'],
  '-': ['...', '...', '###', '...', '...'],
  '+': ['...', '.#.', '###', '.#.', '...'],
  '%': ['#.#', '..#', '.#.', '#..', '#.#'],
  '/': ['..#', '..#', '.#.', '#..', '#..'],
  "'": ['.#.', '.#.', '...', '...', '...'],
  '(': ['.#.', '#..', '#..', '#..', '.#.'],
  ')': ['.#.', '..#', '..#', '..#', '.#.'],
  '<': ['..#', '.#.', '#..', '.#.', '..#'],
  '>': ['#..', '.#.', '..#', '.#.', '#..'],
  '=': ['...', '###', '...', '###', '...'],
  x: ['...', '#.#', '.#.', '#.#', '...'],
  '*': ['#.#', '.#.', '###', '.#.', '#.#'],
  '#': ['#.#', '###', '#.#', '###', '#.#'],
};
